### ISSUE TITLE
Is it possible to exclude a subdomain from crawling?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#102]
I've launched a successful crawl of [Stanford's encyclopedia of Philosophy](https://plato.stanford.edu/), however the site also offers an [archived export](https://plato.stanford.edu/archives/) of its articles which might be redundant with the content available.

Is there any parameter of option that would allow me to _not_ crawl anything under their `/archive` directory?

**Comment by rgaudin** [comment]
Yes, it's rightfully named `--exclude`
