### ISSUE TITLE
Youzim.it task 40d68 requested

### ISSUE THREAD

**Issue by teliten** [openzim/zimit#104]
Youzim.it logo
Ziming of http://washingtonpost.com
100 % (failed)
You request has failed! We are sorry about that.
A number of reasons can lead to a ziming failure. Most of the time, it's an inadequate URL… Please triple check it and create a new request. If that doesn't work, open a ticket in github.

do you have to keep the browser open, that seems silly seeing as you send request and "success" or failure emails. these should be queueed and run in the background,

**Comment by Popolechien** [comment]
`failed to connect to http://washingtonpost.com: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out.`

This being said, trying to get a copy of something that's behind a paywall seems... ambitious.
And to answer your question, you need to leave the browser open only if you did not give an email address on the query page. If you did, then you can close your window. Maybe we should clarify that point on the confirmation page.

**Comment by teliten** [comment]
you're a genius.
ᐧ
