### ISSUE TITLE
Cut Short Endless Loop

### ISSUE THREAD

**Issue by ISJ-439** [openzim/zimit#107]
Hello,

Is there a way to tell the application to simply stop and finish up? As in to have it stop looking for new pages and just wrap the project up? 

Thanks!

**Comment by ISJ-439** [comment]
To be clear, I don't want to kill the progress so far (a month of it), I just want to wrap it up and finalize the recording.

**Comment by kelson42** [comment]
It does that automatically when over with scraping all pages of the target.
