### ISSUE TITLE
Use with localhost websites?

### ISSUE THREAD

**Issue by karelo911** [openzim/zimit#109]
I have a wordpress site deployed locally through xampp. I want to use this utility to export my local site into a zim file. However, I can't seem to access `localhost`. It says `failed to connect to http://127.0.0.1/module: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /module (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86fefcb430>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

**Comment by rgaudin** [comment]
@karelo911 from within the docker container, `localhost` means the container itself so it's normal it's not working.

The easiest is probably for you to use your LAN IP instead of localhost in the URL. Make sure your XAMPP responds on this URL first, of course.
