### ISSUE TITLE
Perseus Hopper

### ISSUE THREAD

**Issue by freedy30** [openzim/zimit#111]
Hi, I'd like to make an offline backup of Tufts University's [Perseus Hopper](http://www.perseus.tufts.edu/)  . I tried but it wouldn't start. 

It probably also has over a thousand pages (maybe?) as it has all the free ancient Greek and Roman texts, each word linked to a dictionary translation. But it's  such an important website, very useful to anyone interested in translating ancient Greek.

Is it possible? Cheers

**Comment by rgaudin** [comment]
@freedy30, this is the repo for the scraper. We're here to assist you with technical difficulties or bugs in said software. 
I'd suggest you try https://youzim.it/ first. It's limited to a 1000 pages but that will answer the question “Is it possible?”.
