### ISSUE TITLE
Error Unable to create schedule: 500: Internal Server Error.

### ISSUE THREAD

**Issue by sobaee** [openzim/zimit#112]
Internal server error

I tried youzim.it online direct zim with these websites:
https://www.unitconverters.net/
https://medicalguidelines.msf.org/viewport/EssDr/english/essential-drugs-16682376.html

But it same you have website errors?

Will you solve this issue soon?

**Comment by rgaudin** [comment]
Thanks for the report ; fixed in https://github.com/openzim/zimit-frontend/commit/17ae9392be062ca294c2d509963922c7f4f77b8e. Please retry.

**Comment by sobaee** [comment]
Thank you for fast response
Internal error has solved but
It still has not able to request a slot!!

This is what I see, no progression even with 7 hours waiting:

"Requesting slot

Your request has been recorded and is awaiting a slot on our infrastructure to run."

**Comment by Popolechien** [comment]
@sobaee Yeah, I see that zimit kept the orders that have been opened since the issue happened and that's like 25 back orders in the queue. I've done a bit of clean-up (duplicates and known fails) but this may take some time to go through it all. Will check again tomorrow.

**Comment by sobaee** [comment]
Thanks a lot 🙏 
I appreciate that

**Comment by Popolechien** [comment]
@sobaee Looks like these jobs crashed unexpectedly, I've restarted them.

**Comment by rgaudin** [comment]
@Popolechien what do you mean crashed unexpectedly? Please open tickets for crashes if it's not clear it's a request error

**Comment by sobaee** [comment]
> @sobaee Looks like these jobs crashed unexpectedly, I've restarted them.

You mean we will have to wait again.

It's fine. I hope it just works.

**Comment by Popolechien** [comment]
So the Medical guidelines [failed once](https://farm.youzim.it/pipeline/8630fd2bdb4ac1ded8f07d16) and [succeded another](https://farm.youzim.it/pipeline/6b80fd2bdb4ac1dee5827d16).
Unit converter [succeeded](https://farm.youzim.it/pipeline/4530fd2bdb4ac1de17f07d16).

Now you need to download the corresponding zim files and run them on Kiwix-serve to see if they're actually ok.
