### ISSUE TITLE
Zimit does not scrape PDF resources that are hosted on a separate domain name.

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#115]
A large number of resources act more as directories of content: they offer link to PDF documents, but the files are actually stored somewhere else, which means that zimit does not pick them up. Two examples of this are https://medcoe.army.mil/borden-tb-ews and https://deployedmedicine.com/

There should be an undestanding from zimit that if the link points to a `.pdf`, `.docx`, _etc._ then it should follow that link and include it as part of the scraping.

**Comment by rgaudin** [comment]
There is already an option to include specific domains (--include-domains). That's what you should use in this case.
