### ISSUE TITLE
successful completion yesterday and all file are not downloadable. 

### ISSUE THREAD

**Issue by mindcloud69** [openzim/zimit#116]
Youzim.it task a8779 succeeded. They all get an error very similar to the below when I try to download the file.

```
<Error>
<script/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>other/www.neoseeker.com_58e286f1.zim</Key>
<RequestId>7357413033AD76CC</RequestId>
<HostId>L7WPhhr2Z88M4FMSIJF2XkWwfC1YJlSrN4NdwbGGJ2/Bv+S/aaCAbyHVTP9daVtNbJFZEpPw2Yhx</HostId>
</Error>
```

The other tasks
Youzim.it task 2a479 succeeded
Youzim.it task fc479 succeeded
Youzim.it task 5f479 succeeded
Youzim.it task 10679 succeeded

**Comment by rgaudin** [comment]
Thank you for the report. Indeed our worker wasn't upload to upload to that bucket. Upload from now on will work. Sorry for the inconvenience.
