### ISSUE TITLE
Key does not exist

### ISSUE THREAD

**Issue by martin8032** [openzim/zimit#117]
I just received an email notification that my ZIM file is ready. But when I click the link, I get the following error message:

**This XML file does not appear to have any style information associated with it. The document tree is shown below.**

```<Error>
<Code>NoSuchKey</Code>
<Message>Der angegebene Schlüssel existiert nicht.</Message>
<Key>other/archiv.klusclassics.ch_eae286f1.zim</Key>
<RequestId>DCD578550FBBC145</RequestId>
<HostId>xZASL/dg1og0RTHXtMzlF/m12foJ06CN/qkKPY2qhNUmMlDtE9Wy8i4+l8Um1gNXwGJRm2IzFhHL</HostId>
</Error>

**Comment by rgaudin** [comment]
Thank you @martin8032 , I misdiagnosed #116 and thus it wasn't fixed. It is now (tested). Further uploads from today 09:46 will suceed.

**Comment by Popolechien** [comment]
@rgaudin Just to be clear because someone else asked - all zim requests before that time will not be uploaded, correct?

**Comment by rgaudin** [comment]
No, only those uploaded (and thus having succeeded) **before** failed to upload and are gone. All the other requests (in-creation and pending-creation) will work fine
