### ISSUE TITLE
Very slow crawling

### ISSUE THREAD

**Issue by LTVA1** [openzim/zimit#118]
I'm maybe a newbie but...
I want to create a zim file of this website: http://scp-ru.wikidot.com/. Sure, it has awful image server and generally is slow, but zimit scans it at 3 pages per minute rate while e.g. cyotek webcopy, while being single-threaded, retrieves about 1-2 pages per second through the same internet connection. I just installed Docker and launched zimit on default machine (```docker-machine create default --virtualbox-no-vtx-check```, ```eval $(docker-machine env default --shell linux)```, ```docker run  -v //output://output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb openzim/zimit zimit --url http://scp-ru.wikidot.com/ --name testscp --workers 10 --exclude="(05command\.wikidot\.com/*|05command-cn\.wikidot\.com/*|97-fz\.rkn\.gov\.ru/*|398-fz\.rkn\.gov\.ru/*|addons\.mozilla\.org/*|aggregator-ua\.wikidot\.com/*|alicebot\.wikidot\.com/*|androidalchemy\.wikidot\.com/*|apps\.apple\.com/*|archive\.org/details/*|arc-scpfoundation\.wikidot\.com/*|artscp\.com/*|away\.vk\.com/*|aws\.amazon\.com/*|backrooms-vn\.wikidot\.com/*|backroom-wiki-cn\.wikidot\.com/*|bettersandbox\.wikidot\.com/*|blog\.naver\.com/*|blog\.wikidot\.com/*|borradores-scp-es-2\.wikidot\.com/*|bvs\.wikidot\.com/*|chaoscomplexityineducation\.wikidot\.com/*|chrome\.google\.com/*|comando05\.wikidot\.com/*|comando05ptbr\.wikidot\.com/*|commandemento5\.wikidot\.com/*|community\.wikidot\.com/*|computers\.amrel\.com/*|connect\.facebook\.net/*|creativecommons\.org/*|creepypasta\.fandom\.com/*|crom\.avn\.sh/*|cs\.wikipedia\.org/*|cs124project-2009\.wikidot\.com/*|cuarteldelo5\.wikidot\.com/*|de\.creepypasta\.wikia\.com/*|de\.wikipedia\.org/*|desktop\.telegram\.org/*|dev\.vk\.com/*|dic\.academic\.ru/*|digitalvomit\.wikidot\.com/*|discord\.com/*|dl\.discordapp\.net/*|docs\.google\.com/*|dowodztwo\.wikidot\.com/*|eais\.rkn\.gov\.ru/*|ejs-in-india\.wikidot\.com/*|en\.wikipedia\.org/*|es\.wikipedia\.org/*|evartist\.narod\.ru/*|ewww\.██████/*|eye-gpma\.ru/*|fondationscp\.wikidot\.com/*|fondazionescp\.wikidot\.com/*|forum\.gamer\.com\.tw/*|forum\.mirf\.ru/*|forums\.somethingawful\.com/*|googleblog\.blogspot\.com/*|gramota\.ru/*|gsb-foundation\.wikidot\.com/*|handbook\.wikidot\.com/*|help\.whale\.naver\.com/*|id\.vk\.com/*|illusionanddream\.bb10\.ru/*|itv\.rt\.ru/*|ja\.scp-wiki\.net/*|journals\.aps\.org/*|ko\.scp-wiki\.net/*|ko5command\.wikidot\.com/*|lafundacionscp\.wikidot\.com/*|lenta\.ru/*|librarians-desk\.wikidot\.com/*|lk\.rt\.ru/*|login\.vk\.com/*|m\.scpfoundation\.net/*|m\.vk\.com/*|m\.youtube\.com/*|mbitcoin\.wikidot\.com/*|medplant\.ru/*|msk\.rt\.ru/*|multitran\.ru/*|myaquaworld\.livejournal\.com/*|nap\.rkn\.gov\.ru/*|notifications\.wikidot\.com/*|o5command-cs\.wikidot\.com/*|o5command-int\.wikidot\.com/*|o5command-th\.wikidot\.com/*|old\.sport-elit\.ru/*|oneeleventwentyten\.wikidot\.com/*|osx86\.wikidot\.com/*|p\.rkn\.qit\.direct/*|planetcalc\.ru/*|play\.google\.com/*|reurl\.cc/*|rostelecom\.ru/*|rt\.ru/*|ru\.m\.wikipedia\.org/*|ru\.wikipedia\.org/*|sandbox\.scpfoundation\.ru/*|sandbox\.scp-wiki\.kr/*|sandboxscpfr\.wikidot\.com/*|scpclassic\.wikidot\.com/*|scp-cs\.wikidot\.com/*|scp-cs-sandbox-2\.wikidot\.com/*|scp-el\.wikidot\.com/*|scp-es\.com/*|scpfoundation\.net/*|scpfoundation\.org/*|scpfoundation\.ru/*|scp-foundation-origins\.wikidot\.com/*|scp-idn\.wikidot\.com/*|scp-int\.wikidot\.com/*|scp-int-sandbox\.wikidot\.com/*|scp-jp\.wikidot\.com/*|scpko\.wikidot\.com/*|scpkosb\.wikidot\.com/*|scpminecraft\.wikidot\.com/*|scp-nd\.wikidot\.com/*|scp-pl\.wikidot\.com/*|scp-pt-br\.wikidot\.com/*|scpsandbox\.wikidot\.com/*|scp-sandbox2-zh\.wikidot\.com/*|scpsandboxbr\.wikidot\.com/*|scpsandboxcn\.wikidot\.com/*|scpsandboxde\.wikidot\.com/*|scpsandboxit\.wikidot\.com/*|scpsandbox-pl\.wikidot\.com/*|scpsandbox-ua\.wikidot\.com/*|scp-tech-cn\.wikidot\.com/*|scp-th\.wikidot\.com/*|scp-th-fanart\.deviantart\.com/*|scp-th-sandbox\.wikidot\.com/*|scp-ukrainian\.wikidot\.com/*|scp-un\.wikidot\.com/*|scpvakfi\.wikidot\.com/*|scp-vn\.wikidot\.com/*|scpvnsandbox2\.wikidot\.com/*|scp-wiki\.net\.pl/*|scp-wiki\.pl/*|scp-wiki\.wikidot\.com/*|scp-wiki-cn\.wikidot\.com/*|scp-wiki-de\.wikidot\.com/*|scp-zh-tr\.wikidot\.com/*|shop\.wikidot\.com/*|snippets\.wikidot\.com/*|soundexpert\.org/*|space\.bilibili\.com/*|st1-21\.vk\.com/*|statcounter\.com/*|steamcommunity\.com/*|support\.google\.com/*|support\.microsoft\.com/*|sweet-ree\.tumblr\.com/*|t\.me/*|takeshiyamada\.weebly\.com/*|tehnoomsk\.ru/*|teleg\.run/*|telegram\.org/*|tradewithsaint\.wikidot\.com/*|tvtropes\.org/*|twitter\.com/*|tycho\.usno\.navy\.mil/*|uk\.wikipedia\.org/*|urlhere\.com/*|ursulavernon\.com/*|vk\.com/*|vocabulary\.ru/*|vradler\.tumblr\.com/*|wanderers-library\.wikidot\.com/*|wanderers-library-cs\.wikidot\.com/*|wanderers-library-ko\.wikidot\.com/*|wanderers-library-pl\.wikidot\.com/*|wanderers-library-vn\.wikidot\.com/*|wanderers-sandbox\.wikidot\.com/*|warning\.rt\.ru/*|web\.archive\.org/*|wiki\.web\.ru/*|wish\.org/*|www\.airwar\.ru/*|www\.aquatrade-nsk\.ru_443/*|www\.bestiary\.us/*|www\.bnti\.ru/*|www\.bolotohod\.ru/*|www\.coindesk\.com/*|www\.dessertsforbreakfast\.com/*|www\.deviantart\.com/*|www\.facebook\.com/*|www\.fanfiction\.net/*|www\.flickr\.com/*|www\.gibbssports\.com/*|www\.gofundme\.com/*|www\.googletagmanager\.com/*|www\.infox\.ru/*|www\.insst\.ru/*|www\.instagram\.com/*|www\.itu\.int/*|www\.kmweg\.com/*|www\.konorama\.ru/*|www\.lingvolive\.com/*|www\.livejournal\.com/*|www\.lockheedmartin\.com/*|www\.mommywantsvodka\.com/*|www\.mrcoffee\.com/*|www\.mspaintadventures\.ru/*|www\.nocorruption\.rt\.ru/*|www\.omnimed\.ru/*|www\.openprocessing\.org/*|www\.paleospot\.com/*|www\.plurk\.com/*|www\.polaris\.com/*|www\.publy\.ru/*|www\.reddit\.com/*|www\.robmulholland\.co\.uk/*|www\.rostelecom\.ru/*|www\.rpcauthority\.wikidot\.com/*|www\.rt\.ru/*|www\.scpwiki\.com/*|www\.scp-wiki\.net/*|www\.scp-wiki-cn\.org/*|www\.telegraph\.co\.uk/*|www\.thebestdinosaur\.com/*|www\.thestranger\.com/*|www\.theuselessweb\.com/*|www\.tvtropes\.org/*|www\.twitter\.com/*|www\.wafflehouse\.com/*|www\.wilddolphinproject\.org/*|www\.youtube\.com/*|www\.когр\.рф/*|www1\.fips\.ru/*|youtu\.be/*|youtube\.com/*|zakupki\.rostelecom\.ru/*)" --waitUntil domcontentloaded```) and here I am, scanning only first several pages at very slow rate and then completely stopping.

It seems like it has internet connection but something is wrong since it gets first pages.

System: Windows 10. CPU: Intel i5-8600. Git Bash MinGW x64 terminal. VirtualBox 6.1.34 r150636 (Qt5.6.2).

**Comment by LTVA1** [comment]
Installing docker desktop on different machine and enabling ```Expose daemon on tcp...``` and ```Use docker compose v2``` seems to fix the issue. Not sure if it will succeed with creating zim file, but crawl itself works fine, roasting my laptop with 30 workers but crawling at 1.6 pages per second after first several minutes of lower speeds.

**Comment by LTVA1** [comment]
Ok, so after relaunching laptop I still have the issue

**Comment by LTVA1** [comment]
New details: it sort of starts working, but gets to some speed, then page counter stops at some value and speed starts slowly decreasing

**Comment by LTVA1** [comment]
If this happens, network usage drops to 0.1 Mbps and stays at that speed

**Comment by NielsGx** [comment]
on a fedora vps, with 4 cores, 16gb ram, I get like 0.15 pages/s

is this normal??? way to slow

**Comment by rgaudin** [comment]
As for #124, I'd advise to look for answers on browsertrix. We plan to update zimit with latest browsertrix-crawler soon to benefit from the many improvements there's been. I am waiting for 0.6 so we can use the sizeLimit param.
