### ISSUE TITLE
Doesn't scrape foreign domain resources

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#12]
CDN hosted resources are apparently not captured

Capturing `https://isago.ml/` I get the following

```
Failed to load resource: http://localhost:9999/isago.ml_2020-09/A/isagoml_2020-09/mp_/https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css the server responded with a status of 404 (Not Found)
```

**Comment by ikreymer** [comment]
This was caused by the `-a` flag not being included in `warc2zim`, which means it only includes URLs from the domain of the URL. But I wonder if that should just be the default in warc2zim?

**Comment by rgaudin** [comment]
OK, then that's linked to the exposure of all warc2zim args in zimit (regarless of whether you want to set it as default there)

**Comment by kelson42** [comment]
@ikreymer To me `warc2zim` per default should scraper external resources. We have here a symptom of a weakness in `warc2zim` IMO.

**Comment by ikreymer** [comment]
It's just a config option to filter, can be toggled the other way by default.

**Comment by kelson42** [comment]
> It's just a config option to filter, can be toggled the other way by default.

yes, and the default value is not the right one IMO and this is why we have now this ticket and discussion.

Default configuration should be the one we use most of the time.
