### ISSUE TITLE
bad_malloc creating www.vrsurgeryonline.com

### ISSUE THREAD

**Issue by webinjection** [openzim/zimit#123]
https://www.vrsurgeryonline.com/

Gets to 90% then fails, not sure what I'm doing wrong?

**Comment by rgaudin** [comment]
@webinjection, there is not enough information in this ticket to help you. What does “fails” mean in this case? How do you know it's 90% ? What did you use? youzimit website or zimit? If the latter, please share you command line and logs.

**Comment by webinjection** [comment]
Thanks for looking into this.   I used the youzimit website
[https://youzim.it/ linked from https://www.kiwix.org/en/documentation/]

The process starts and the progress bar gets to approximately 90% before it cuts out and shows the failure message.
I did not select any of the advanced options and the exact address I typed in was "https://www.vrsurgeryonline.com" including the https:// but not the trailing slash

**Comment by rgaudin** [comment]
Thank you @webinjection ; I've checked the log and it fails in a [known and fixed libzim bug](https://github.com/openzim/libzim/issues/578):

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

We've just released a new version of libzim and pylibzim and we are awaiting a couple of issues to be fixed before making a new zimit release that would solve your problem.

Unfortunately, I don't have any workaround to offer in the mean time.

**Comment by Popolechien** [comment]
FWIW I've sent a note to vrsurgeryonline.com asking for permission to reproduce and distribute their content on Kiwix.

**Comment by webinjection** [comment]
All good - thank you for looking into it and helpful to know it wasn't because I was doing something wrong on my end.
