### ISSUE TITLE
Only get the main page of fextralife wiki

### ISSUE THREAD

**Issue by NielsGx** [openzim/zimit#124]
Hello, I'm trying to scrape a fextralife wiki, but it only does the first mainpage, even when I manually set the sitemap.
I don't get it, can someone help ? thanks

`sudo docker run  -v /output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb openzim/zimit zimit --url https://eldenring.wiki.fextralife.com/ --name "Elden Ring - Fextralife wiki" --workers 4 --exclude="signin|signup" --useSitemap https://eldenring.wiki.fextralife.com/sitemap.xml`

**Comment by rgaudin** [comment]
Hi @NielsGx, I advise you open a ticket on https://github.com/webrecorder/browsertrix-crawler as this is the tool responsible for the crawling stage of zimit. I wouldn't have much to share on the matter. Please note that zimit still use an older release: 0.3.2
