### ISSUE TITLE
Scraping failing at 93 and 94% with std::bad_alloc error

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#127]
So I've tried to scrape [armypub](https://armypubs.army.mil/) which seems at first to be a pretty basic website with a collection of PDF files. Scraping goes fine for a while but both run I tried crashed at [94](https://farm.openzim.org/pipeline/20e1021eea77ce41d344f926/debug) and [93%](https://farm.openzim.org/pipeline/ce54221eea77ce417c4e0a26/debug) completion, both time with after throwing an instance of `std::bad_alloc`

Am I right to assume that the problem could be solved by throwing more memory or storage in the recipe parameters?

**Comment by rgaudin** [comment]
No you're not ; it's a libzim issue that's been fixed. We need to make another zimit release

**Comment by rgaudin** [comment]
See #123

**Comment by rgaudin** [comment]
Recipe is using zimit 1.1…

**Comment by Popolechien** [comment]
welp. Restarted using `latest`

**Comment by Popolechien** [comment]
Still failing.

**Comment by kelson42** [comment]
@Popolechien Last run is fine, see https://farm.openzim.org/pipeline/e89db0e5d71560eed8b64b26

**Comment by Popolechien** [comment]
Nice. I've poked around a bit and it looks fine. I've pinged the original requester so they can have a deeper look at it and confirm.
