### ISSUE TITLE
Certificate Trust Store has to be updated

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#128]
We can not scrape all Web sites with legitimate SSL certificate, see for example:
https://farm.openzim.org/pipeline/535f9139ef52f9a93e264a26/debug

**Comment by rgaudin** [comment]
Tough one! zimit is based on [browsertrix-crawler](https://github.com/webrecorder/browsertrix-crawler) image. The one we currently use is based on debian:buster but master is based on ubuntu:bionic (no reason for this quite old version [in the commit](https://github.com/webrecorder/browsertrix-crawler/commit/f57818f2f6b28824eaf2d62f170b4932793879bc)).

I've tried different update strategies (package, python packages, [manual](https://curl.se/docs/caextract.html)) but then realized that the hypothesis is wrong as a fresh ubuntu is affected as well:

```
docker run -it ubuntu:latest bash -c "apt update && apt install -y ca-certificates curl && curl https://www.canal-u.tv/"
```

Even latest curl image (a month old) fails

```
docker run -it curlimages/curl:latest curl https://www.canal-u.tv
```

Works fine on my local curl and in browsers though… I don't know what's going on. I've [tested SSL config](https://www.ssllabs.com/ssltest/analyze.html?d=www.canal-u.tv) and I do see mention of incomplete chain of trust
<img width="1008" alt="Screen Shot 2022-06-13 at 11 22 01" src="https://user-images.githubusercontent.com/57929/173343242-8879390b-193c-46c6-a693-fdad8e2ab6c8.png">
<img width="1029" alt="Screen Shot 2022-06-13 at 11 22 08" src="https://user-images.githubusercontent.com/57929/173343256-519b39a8-16ed-43cc-9d21-34172df6e591.png">

**Comment by kelson42** [comment]
I'm not sure there is anything else we can build... maybe an `--insecure` option?
