### ISSUE TITLE
Unable to scrape h2g2.com

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#136]
With Zimit 1.2.0

failed to connect to https://h2g2.com/: HTTPSConnectionPool(host='h2g2.com', port=443): Read timed out. (read timeout=10)

but https seems ok

https://farm.openzim.org/pipeline/3f49a0e5d71560ee3c702b26/debug

**Comment by rgaudin** [comment]
Works with master for me but:
- I couldn't reproduce the issue with 1.2.0
- Launched another run on zimfarm and it failed after a minute of crawling
- Launched 1.2.0 on my machine with exactly same args and it's been running for 20mn already…
- Launched another 1.2.0 run on zimfarm and it seems to be running. For some reason `michaelblob` worker fails to run `:dev` image. Looks like a worker issue (disk ?)

I edited recipe as it included a custom CSS for another website… 🙄
Also, h2g2 lists a favicon that is missing so it fails to create the illustration. Fixed it in warc2zim but not released and thus not included in zimit. You have to specify one in the mean time (I did).
