### ISSUE TITLE
youzimit fails on https://fresqueduclimat.org/memo/fr-FR/game/grid/

### ISSUE THREAD

**Issue by npalix** [openzim/zimit#137]
I tried to build the ZIM file for 
the website https://fresqueduclimat.org/memo/fr-FR/game/grid/
under the task 62928 which failed.

It was with the default option.

Any hint ?
The website seems to use svg (Inkscape) images.

**Comment by rgaudin** [comment]
Thank you, that's an interesting bug. The website has an unwise configuration in that it redirects to port `443` explicitly so we set the *homepage* to that final URL while the crawler (Chrome) keeps the unspecified one as it's the default port.

```
curl -I https://fresqueduclimat.org/memo/fr-FR/game/grid
HTTP/2 301
date: Wed, 22 Jun 2022 08:00:15 GMT
content-type: text/html; charset=iso-8859-1
server: Apache
location: https://fresqueduclimat.org:443/memo/fr-FR/game/grid/
```

```
Unable to find WARC record for main page: https://fresqueduclimat.org:443/memo/fr-FR/game/grid/, ZIM not created
```

Will fix this edge case.
