### ISSUE TITLE
Bad scrape of courses.lumenlearning.com_en_all_2022-06.zim

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#140]
The file `courses.lumenlearning.com_en_all_2022-06.zim` should be >11GB, but is only 19MB. The previous version `courses.lumenlearning.com_en_all_2021-03.zim` is 11GB.

**Comment by Popolechien** [comment]
Looks like a regression because the last version has been done using the latest zimit.
https://farm.openzim.org/recipes/courses.lumenlearning.com

**Comment by rgaudin** [comment]
Probably a recipe issue given it lasted 2mn versus several hours in the past (last ZIM is one year old, newer attempts failed due to the bad_malloc bug).

Should we just move all zimit recipes to dev and move them back individually after a successful run?

**Comment by Popolechien** [comment]
> Should we just move all zimit recipes to dev and move them back individually after a successful run?

sounds like the reasonable way forward. I'll do it, there aren't this many.

**Comment by rgaudin** [comment]
Courses are hosted on www.coursehero.com now. Added this domain to scope and rescheduled.

**Comment by rgaudin** [comment]
Was a recipe issue: as mentioned above, resources are split accross three domains. Other issue was that coursehero has a captcha that I could bypass with a custom UserAgent. Running now…
