### ISSUE TITLE
scraper fails because of missing image

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#142]
Job [a39758bd2968338c93efbb26](https://farm.openzim.org/pipeline/a39758bd2968338c93efbb26/debug) failed after crawling 100% of the target (bookdash.org) and only error I can see in the log is `raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/app/book-dash-logo_265x132.png'`

Seems to me rather benign that it should not crash the whole thing.

**Comment by rgaudin** [comment]
It's in warc2zim and it's been fixed but zimit is using latest release. I'll use warc2zim master in between releases so we have the ability to use and test non-released code for both at once.
