### ISSUE TITLE
Army publishing ZIM appears to have no landing page

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#143]
I haven't investigate this ZIM properly, but Kiwix Serve doe snot appear to provide a landing page:

https://library.kiwix.org/armypubs_en_all_2022-06/A/armypubs.army.mil/

The landing page is empty, and pressing the random button (several times) fails to open any useable page either.

**Comment by kelson42** [comment]
@rgaudin Can we please remove this ZIM file? The recipe is broken AFAIK. Not even sure this is a problem with Zimit?

**Comment by Popolechien** [comment]
@kelson recipe is not broken (works for me) and it has something to do with service workers IIRC) but I agree this is suboptimal. 

This blank screen thing happened to me with Zim files generated with latest release of zimit.

**Comment by rgaudin** [comment]
There are **several** tickets for this ZIM here and at warc2zim.

**Comment by kelson42** [comment]
@rgaudin Ok, but can you plase remove the ZIM from download.kiwix.org?

**Comment by rgaudin** [comment]
I need clear directions otherwise this can't work.
Was in dev, works in chrome but buggy in FF (ticket in warc2zim).
Now it's in other... Should either be in dev or zimit.

**Comment by kelson42** [comment]
@rgaudin As long as a ZIM is not OK it should not be in the "zimit". Zimit files should be in "zimit" directory, not "other". In general we should not distribute ZIM files which are severly broken.

**Comment by Popolechien** [comment]
@kelson42 At this stage I would argue we discontinue zimit altogether (including or even starting with youzim.it)

**Comment by kelson42** [comment]
@Popolechien If new version is too buggy, then we should rollback.

**Comment by Popolechien** [comment]
Old version is pretty much useless on most sites.

**Comment by kelson42** [comment]
@Popolechien Lets discuss this separatly. For the moment, it is important published ZIM files are OK and ticket are tracked properly.

**Comment by Jaifroid** [comment]
> @kelson42 At this stage I would argue we discontinue zimit altogether (including or even starting with youzim.it)

That would be a lot of work to unwind considering it mostly works...

**Comment by Popolechien** [comment]
@rgaudin I know but I just wanted to have it written somewhere so we know which zims to test eventually if/when we get a fix ^^

**Comment by rgaudin** [comment]
I guess that “we” is you then because I won't be digging up closed, duplicate tickets for URLs to test… 🙃

**Comment by Popolechien** [comment]
You would be surprised!
