### ISSUE TITLE
No new job started for 8 days

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#144]
Looking at farm.youzim.it I see a backlog going 15 days and no ongoing job. The last few failed/completed jobs happened over the past 24hours but otherwise nothing for 8 days before that. 

Any idea what happened and how we could better know when something seems amiss like in the present case?

**Comment by rgaudin** [comment]
> Any idea what happened?

There were too several-days running tasks that I eventually canceled on Monday as part of the weekly routine.

<img width="1125" alt="Screen Shot 2022-07-06 at 10 08 40" src="https://user-images.githubusercontent.com/57929/177526878-7575ae37-0fcb-44ff-a43f-d4fe39991d9d.png">
