### ISSUE TITLE
add day to naming

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#146]
hi,
when I create zim-files it automatically adds _yyyy-mm.zim to the name.
I need to have the day in the name too.
Manually renaming every file is not handy.
Please add an option for this or an option to disable adding date so that I can include this in naming.
Thanks a lot.

**Comment by rgaudin** [comment]
There's a `--zim-file` parameter that you can set to whatever fits your need. If it is included inside, `{period}` is replaced with YYYY-MM.
