### ISSUE TITLE
possible to archive listings with slideshow/gallery? 

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#147]
hi, I'm trying to archive a site like this:
https://www.yachtall.com/de/boot/westerly-pentland-417141
using this command:
docker run --rm -v /path/to/zimit/output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb openzim/zimit zimit --url https://www.yachtall.com/de/boot/westerly-pentland-417141 --name westerly-pentland --workers 4 --waitUntil domcontentloaded --timeLimit 69 --depth 1
But I will only get the first three pictures archived.
Same at youzim.it
Anything I could do about it?

**Comment by rgaudin** [comment]
It seems that the following images are not loaded on page load but only upon click ; which makes sense from a developer's perspective: you want users to be able to see the first images instantly but you don't want them to load 25 of them if there are greater chances that those won't be visited.

Here's a bot of the source code

```html
<div class="thumbglry-box" id="thumbglry_417141_0_img_18" style="left: 360%" data-loaded="false"><img src="https://static.yachtall.com/sharedimg/layout/loading-wheel.gif" alt="" data-src="https://img.yachtall.com/image-sale-boat/westerly-pentland-thumb-41714172caedecad.jpg"></div>
```

Notice how the image source is the loading GIF (that the browser got) but the actual image is in a custom `data-src` attribute that is probably used by some custom JS code. `data-loaded="false"` reinforces that probability.

I don't have an answer for how to gets the images or whether it's possible at all. You should ask this on the [crawler repository](https://github.com/webrecorder/browsertrix-crawler).
