### ISSUE TITLE
unable to use zimit-file behind apache reverse proxy

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#148]
read UPDATE here: https://github.com/openzim/zimit/issues/148#issuecomment-1296971272

I created this simple zim-file via:
docker run --rm -v /path/to/zimit/output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb openzim/zimit zimit --url https://dict.cc --name dict.cc --workers 2 --waitUntil domcontentloaded --depth 1
[dict.cc_2022-07.zim.zip](https://github.com/openzim/zimit/files/9184372/dict.cc_2022-07.zim.zip)
Hosting it via command: kiwix-serve -p 10231 -r kiwix /path/to/kiwix/*.zim
But if I open it in https://example.com/kiwix/dict.cc_2022-07/C/A/dict.cc/ or in http://localhost:10231/kiwix/dict.cc_2022-07/C/A/dict.cc/ I would only get a blank page. Only search results & previews are loaded correctly.
Hosting it via command: kiwix-serve -p 10232 /path/to/zimit/output/*.zim
I will see the actual result in http://localhost:10232/dict.cc_2022-07/C/A/www.dict.cc/
Using apache reverse proxy like this:
```
<Location "/kiwix/">
  AuthType Basic
  AuthName "Wrapper auth"
  AuthUserFile "/path/to/my/passwords"
  Require valid-user
        ProxyPreserveHost       On
        ProxyPass               "http://localhost:10231/kiwix/"
        ProxyPassReverse        "http://localhost:10231/kiwix/"
</Location>
Redirect permanent /kiwix /kiwix/
```
Anything I can do to make this work?
Thank you in advance

**Comment by ristein** [comment]
Another thing: where can I report about files from the official library?
Both files fas-military-medicine I can only few via localhost, not via https, blank page there.
This might even be related...
https://download.kiwix.org/zim/zimit/fas-military-medicine_en_2022-05.zim

**Comment by rgaudin** [comment]
Thank you @ristein ; 

First, I'd like to invite you to use the latest versions of those softwares. When using zimit, please use the `openzim/zimit:dev` image as a few issues have been fixed but not released yet.

Kiwix-serve as well, https://download.kiwix.org/release/kiwix-tools/ has the latest version. You'll notice there's no `C/` in the URL with the new version. That will make discussions easier.

I haven't tested your WARC but used the fas-military ZIM instead. I don't get a blank page that says `Sorry, the URL https://irp.fas.org/doddir/milmed/index.html is not in this archive.` using my FF browser.

ServiceWorker sends a `404` for `http://localhost:9999/yolo/fas-military-medicine_en_2022-05/A/mp_/https://irp.fas.org/doddir/milmed/index.html`.

Now if I try on a **clean** browser (FF, Chrome, Safari), the ZIM works as expected and the very same URL returns `200`. The reason for the failure is unclear. Playing with the `&root=` parameter of the `sw.js` seems to make it work on FF some times but breaks the other ones and it's unreliable.

@ikreymer can you please take a look. It seems we've introduced a regression at some point regarding this.

**Comment by ristein** [comment]
I switched to openzim/zimit:dev in docker and kiwix-tools 3.3.0 (dev) instead of 3.1.2 (main).
Instead of the white pages I now see `Sorry, the url https://dict.cc/ is not found on this server` at example.com/kiwix/dict.cc:dev/A/dict.cc/ and at http://localhost:10231/kiwix/dict.cc:dev/A/dict.cc/ (urlRootLocation problem with selfmade zim-files).
When clicking on a search result I would get to the original dict.cc webpage after several redirects versus blank page on 3.1.2.

military medicine now gives me `Sorry, the URL https://irp.fas.org/doddir/milmed/index.html is not in this archive. [Try Live Version?](https://irp.fas.org/doddir/milmed/index.html)` instead of a blank page at example.com/kiwix/fas-military-medicine_en_2022-05/A/irp.fas.org/doddir/milmed/index.html
but is still working on localhost:10231/kiwix/fas-military-medicine_en_2022-05/A/irp.fas.org/doddir/milmed/index.html
(both via urlRootLocation)

in a private FF window opening military-medicine shows correct page for 1/10 sec then the complaint about private window, hitting backwards repeats the 1/10 sec.
In Min-browser my selfmade zim-file is working at http://localhost:10231/kiwix/dict.cc:dev/A/dict.cc/
![image](https://user-images.githubusercontent.com/55446611/181646653-c305c8be-67b4-47ce-b1be-6cbec4fec727.png)

**Comment by Popolechien** [comment]
FWIW I guet a somewhat similar behaviour with ncert-audiobooks_en_all_2022-07

**Comment by rgaudin** [comment]
@Popolechien this ticket is about a problem with a specific kiwix serve option. Your comment is not related at all.

**Comment by Popolechien** [comment]
@rgaudin Ok, I added because of the seemingly identical behaviour. I'll open a separate ticket.

**Comment by ristein** [comment]
I just played around again and found that urlRootLocation has nothing to do with it, sorry for that.
In Apache I now temporarily redirect my example.com to "http://localhost:10231/kiwix/" instead of example.com/kiwix/. So the urlRootLocation option is not needed anymore but the problem persists anyway: localhost:PORT works fine, but example.com does only work with official zim-files not with selfmade ones. Here files created with "openzim/zimit:dev" say "Sorry, the url https://dict.cc/ is not found on this server", files created without ":dev" just be blank underneath the header.
So the problem seems to be somewhere in Apache's ProxyPassReverse, which changes headers from localhost into example.com so that the clients browser won't see the internal link.
Would be great to be able to host any crawled webpage accessible remotely, not only via localhost.
But I can totally understand if you developers got better stuff to do.

Might be related:
https://github.com/openzim/zimit/issues/110
https://github.com/kiwix/kiwix-tools/issues/507

**Comment by rgaudin** [comment]
Pretty sure this is #154 and not reverse-proxy related.

**Comment by ristein** [comment]
I tested on Version 3.4.0 in docker and see the same behavior as before.
"Sorry, the url https://dict.cc/ is not found on this server"

**Comment by kelson42** [comment]
@ristein You confirm that it works fine without proxy, so the problem is the proxy. Regarding fixing the problem, I think here nobody is super familiar with Apache because we don't use it. But we serve such ZIM files behind a reverse proxy (nginx) and it works. Therefore, this is probably either a misconfiguration or a bug of Apache. In both case, it seems to me we might face difficulties to give you more help here.

**Comment by kelson42** [comment]
Nothing more we can do here, this is a chanlange with the configuration of the Apache reverse-proxy.

**Comment by ristein** [comment]
this now works as expected:
I can create zim-files using docker zimit and when serving them in kiwix-serve they also work with apaches reverse proxy
