### ISSUE TITLE
several extra links

### ISSUE THREAD

**Issue by dan83g** [openzim/zimit#149]
Is it possible to add a several extra links. For example, if the site has a dynamic menu and not all content is scraping.
Thank you.

**Comment by rgaudin** [comment]
I believe `--useSitemap` can be used for this. Doesn't have to be on the same domain.

Should that not work for you, I'd advise you open a ticket at [browsertrix-crawler](https://github.com/webrecorder/browsertrix-crawler) which is the crawler zimit uses so any improvement to the scraping process would happen there.

**Comment by dan83g** [comment]
Please tell me the format of the sitemap file. I tried xml but it didn't work.

**Comment by rgaudin** [comment]
Guess you figured it out https://github.com/webrecorder/browsertrix-crawler/issues/151#issuecomment-1207485538 👍
