### ISSUE TITLE
two stats files in same folder override each other

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#150]
hi,
if I run zimit via docker and mount the same folder for two instances running at the same time the stats files are both being overwritten by both instances.
I will mount different subdirectories for each container from now on, might be an enhancement tho

**Comment by kelson42** [comment]
Îm not sure here what is the problem or what could be a better solution.

**Comment by rgaudin** [comment]
I suppose you missed the `--statsFilename` param… Please reopen if I misinterpreted the problem.

**Comment by ristein** [comment]
no, I user --statsFilename for both containers, with different names.
when I use watch -n1 cat stats.txt, I see done-pages jump Ford and back from the count of one container to the one of the other container, that I started earlier so higher count.

**Comment by rgaudin** [comment]
Oh I see, it's not related to the two parallel scrapes I believe. The numbers are updated always as new links are found in newly scraped pages. Could you test that it's what you're experiencing?

**Comment by ristein** [comment]
I'm not sure, what I should test, since I don't see which crawl accesses the file.
But it might be caused by the fact that crawl.json is no unique name.

**Comment by rgaudin** [comment]
Ah… OK ; I eventually understand you're problem. Indeed, inside the specified `--output` directory, zimit will create `crawler.json` and `warc2zim.json` temporary files regardless of the `--statsFilename` specified.
If running two zimit tasks using the same `--output` directory, containers would constantly overwrite those files, making the progress unusable.
