### ISSUE TITLE
Internet Encylopaedia of Philosophy (Type 1) could be moved out of `dev` and returned to `other`

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#156]
Having done a fair amount of testing of this ZIM on Kiwix Desktop and for the purpose of fixing support in KJSW, I don't see any issue with the ZIM at least in these two readers (other than #155, but this was present previously and the readers work around it). I haven't tested on Android.

This is a relatively static ZIM. I don't think it needs to be in `dev` any more, especially as the version in `other` is getting quite old now (2022-02).

Concretely, I am referring to: `internet-encyclopedia-philosophy_en_all_2022-07.zim`.

**Comment by Popolechien** [comment]
Moved recipe to /zimit and requested a run on the zimfarm.

**Comment by Jaifroid** [comment]
Thanks @Popolechien . I confirm that the new August IAP ZIM in the `zimit` directory works well and is appears to be a good scrape. JFYI There are still two old versions of this ZIM in the `other` directory. I think they should either be moved to `zimit` or else deleted.

**Comment by Popolechien** [comment]
I made a request for deletion : [zim-requests/issues/461](../../zim-requests/issues/461)
