### ISSUE TITLE
Ready Gov ZIM (Type 1) could be moved out of dev and into zimit

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#157]
I have done a fair amount of testing with the Type 1 ("no-namespace") version of this ZIM: `www.ready.gov_es_2022-07.zim` (Spanish-language version). It all seems to work fine (see console log output of Kiwix JS PWA below, with diagnostic info). It also works fine when served from Kiwix Serve over localhost (the Kiwix Desktop workaround). Now while this specific ZIM is the Spanish version, in fact it contains all the other languages as well, but the landing page is the Spanish one (as far as I can tell, this is the only difference, in principle, between the Spanish-language and English-language versions). In any case, I think it is safe to point the zimfarm recipe for the Spanish-language version to zimit instead of dev, since the last scrape was successful:

https://farm.openzim.org/recipes/ready-gov_es

Regarding the English-language version, the last scrape of that actually failed (it was way too small, even though it says succeeded on this list):

https://farm.openzim.org/recipes/ready-gov_en

But it would be worth re-trying it, as that may have been a temporary error.

![image](https://user-images.githubusercontent.com/4304337/188500159-c4b86380-7e0e-43c3-a270-04a8638fd6cf.png)

<img width="765" alt="image" src="https://user-images.githubusercontent.com/4304337/188500590-b743cbdd-bae4-47c7-938d-13c8651a5681.png">

**Comment by rgaudin** [comment]
Moved ES version ; restarted EN. Still running after 40mn (previous one was 20s) so it's promising. Will check later and move to `zimit` as well if it succeeds.

**Comment by rgaudin** [comment]
Moved EN as well
