### ISSUE TITLE
Add support for mycorrhiza.wiki (mediawiki alternative)

### ISSUE THREAD

**Issue by Rexadev** [openzim/zimit#159]

**Comment by rgaudin** [comment]
Didn't see that one; it's not an appropriate request for zimit. It should be a [zim-request](https://github.com/openzim/zim-requests/issues/new?assignees=&labels=&template=new-zim-request.md&title=New++request%3A+). I didn't transfer as it doesn't include the requested info.

**Comment by Rexadev** [comment]
@rgaudin please delete this issue
