### ISSUE TITLE
`developer.mozilla.org_en_all_2022-07.zim` (Type 1) could be moved out of `dev` and into `zimit`

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#160]
Currently there are two older Type 0 versions of this archive in the `zimit` directory on download.kiwix.org. However, the newest version in the `dev` directory - `developer.mozilla.org_en_all_2022-07.zim` - is Type 1 (no-namespace) and seems a good release candidate to me. I have tested it fairly extensively on both Kiwix Serve (via Kiwix Desktop), and on pwa.kiwix.org. The only issue I found is that the **_very few_** embedded YouTube videos aren't scraped, but it has almost zero impact, and I think that would be fixed by running a new crawl at some point with the latest Zimit/warc2zim code. It seems safe to move this ZIM to `zimit`.

[I haven't been able to test on Android, because the versions in `dev` can't be downloaded in the Android app, and I've been unseccessful in trying to add it to the app's Library from the Android file system.]

**Comment by rgaudin** [comment]
Done. Library will sync soon.
