### ISSUE TITLE
Can not read zim file of https://en.scratch-wiki.info/

### ISSUE THREAD

**Issue by patiencing** [openzim/zimit#162]
- Target website: https://en.scratch-wiki.info/
- Request number: https://youzim.it/d0e92ba90e63be3a0d03a536

Zimit scraped the site https://en.scratch-wiki.info/, and create a zim file with size of 90.3 MB.
But Kiwix cannot read this zim file.

**Comment by rgaudin** [comment]
@patiencing there are multiple Kiwix reader ; which one is it that “cannot read this zim file” and what is exactly hapenning?

First of all, please check the warning on top of https://github.com/openzim/zimit and the second FAQ entry at https://youzim.it/

**Comment by patiencing** [comment]
> @patiencing there are multiple Kiwix reader ; which one is it that “cannot read this zim file” and what is exactly hapenning?
> 
> First of all, please check the warning on top of https://github.com/openzim/zimit and the second FAQ entry at https://youzim.it/

I use Kiwix desktop 2.1.2 on Mac.

**Comment by rgaudin** [comment]
It doesn't support zimit-made ZIM files unfortunately. on macOS, the easiest solution would be to use [Kiwings](https://github.com/technusm1/kiwings) which starts a `kiwix-serve` server that you access from your web browser.

**Comment by patiencing** [comment]
> It doesn't support zimit-made ZIM files unfortunately. on macOS, the easiest solution would be to use [Kiwings](https://github.com/technusm1/kiwings) which starts a `kiwix-serve` server that you access from your web browser.

It works, thank you!
