### ISSUE TITLE
Default ZIM filename is incomplete

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#164]
Look at https://farm.openzim.org/recipes/coopmaths. The filename created is `coopmaths_2022-12.zim`. It should be `coopmaths_fr_2022-12.zim`.

**Comment by rgaudin** [comment]
@kelson42 ?

**Comment by rgaudin** [comment]
- https://github.com/openzim/overview/wiki/Naming-Convention
- https://wiki.openzim.org/wiki/Metadata
