### ISSUE TITLE
Permanently move `developer.mozilla.org_en_all` to zimit directory

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#169]
Following on from #160, I noticed that `developer.mozilla.org_en_all_2023-01.zim` appears in the `dev` directory still instead of in the publicly accessible `zimit` archive. I tested the January 2023 version using Kiwix Serve and Kiwix JS for Windows and Linux (screenshots below). I can't find anything wrong with the archive (after browsing several articles and using full-text search).

The only thing to note is that this archive is approx 3 x larger than the version produced in July 2022 (1GB compared with 300MB). I assume this is simply because more content has been scraped.

I think it would be safe to move this archive to `zimit` and also to ensure that future scrapes are uploaded directly to `zimit`, unless you prefer a different workflow.

![image](https://user-images.githubusercontent.com/4304337/214776745-8e670b1f-b6bb-4032-b683-4583dbbb40bb.png)

**Comment by kelson42** [comment]
@Jaifroid Can you please put this conent specific requests on openzim/zim-requestd

**Comment by Jaifroid** [comment]
@kelson42 Sure. I think the reason why these checks have always been posted here is that they were (at least originally) checks that the Zimit scraper was working as designed, rather than it being about the specific ZIMs.

**Comment by rgaudin** [comment]
> @Jaifroid Can you please put this conent specific requests on openzim/zim-requestd

@kelson42 this is one of the few original content we (you) identified to validate zimit version 1.0

**Comment by rgaudin** [comment]
Edited the recipe and moved latest ZIM to `zimit/`
