### ISSUE TITLE
Permanently move `lowtechmagazine.com_en_all` to zimit directory

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#170]
Similar to #169, `lowtechmagazine.com_en_all_2023-01.zim` seems to be a good scrape, and as this is a largely static web site, it would seem safe to let future versions go straight to `zimit`.

![image](https://user-images.githubusercontent.com/4304337/214780346-33f21541-79b9-48f7-93ed-ca650cbb154a.png)

**Comment by rgaudin** [comment]
Edited the recipe and moved latest ZIM to `zimit/`.

Should we have a different update strategy for zimit ? Or for some zimit recipes? Our process if to test at introduction and then we publish directly all updates (monthly 99% of the time).
Given zimit is *somewhat fragile* and that the kind of testing required to ensure content is still usable will not (in foreseeable future) be doable by zimcheck (and thus understood by the CMS), should we do things differently?

**Comment by Jaifroid** [comment]
My tuppence: ideally each new, untested recipe should produce a test ZIM (in dev, as at present). But what is needed is that (ideally) the person who created the recipe should then check the resulting ZIM with, at a minimum, Kiwix Android and Kiwix Serve. If it's passing manual checks, then it's probably safe to move to zimit.

The problem is that at present new recipes are being created, but not being tested except _ad hoc_ (I tend to test the ZIMs I'm personally interested in, or to test support for new sites in the KJSWL reader).

**Comment by rgaudin** [comment]
@Jaifroid that's the process that we are trying to follow albeit everyone wasn't on the same page which led to those untested ZIMs. Please consider and expect that new recipes will follow this procedure.
