### ISSUE TITLE
Mozilla developer zim file is broken

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#171]
https://library.kiwix.org/viewer#developer.mozilla.org_en_all_2023-02/A/developer.mozilla.org/en-US/

i can not read any of the guides, i always get a 404

**Comment by rgaudin** [comment]
It's a recipe issue.

[The recipe](https://farm.openzim.org/recipes/developer.mozilla.org_en/config) crawls `https://developer.mozilla.org/en-US/`

A good number of links from the main page points to the `https://developer.mozilla.org/en-us/` prefix (notice the case in the last part!)

Some other pages links correctly to the `en-US` prefix and where thus captured and are working:


https://library.kiwix.org/content/developer.mozilla.org_en_all_2023-02/A/developer.mozilla.org/en-US/docs/Learn/CSS

**Comment by Popolechien** [comment]
Honestly if most of the front page links fails then the whole thing is a failure (end user has no way of knowing that they need to dig around to find stuff). I would either remove the file until we figure out a fix, or remove file and recipe altogether.

**Comment by kelson42** [comment]
@rgaudin I don't understand your comment... maybe an error in the urls?

**Comment by rgaudin** [comment]
@Popolechien if entering a URL is the maximum effort we're willing to make to create a zimit ZIM, then yes.

@kelson42 I guess the web server is case insensitive so they have links to both `en-US` and `en-us`. Our recipe targets `/en-US/` prefix.

**Comment by kelson42** [comment]
@rgaudin got it, sorry.

**Comment by Popolechien** [comment]
`/en` redirects to `en-US`, and removing the language variant will lead us to capture all language variants. Which one is most likely to work in a satisfactory manner?

**Comment by rgaudin** [comment]
I think we should be good with just setting the `include` option. Something like `(\/en-us|en-US\/)` **might** work but we should test because I'm not sure about the format and how it's interpreted.

Can you try and relaunch in `dev` ? It's only 6h
