### ISSUE TITLE
The zim file created by https://youzim.it/ might be bigger than the original website

### ISSUE THREAD

**Issue by Leirda01** [openzim/zimit#172]
As suggested [here (fr)](https://linuxfr.org/news/jubako-et-arx-un-conteneur-universel-et-son-format-d-archive#comment-1905862), I opened this issue because, in some cases, the zim file returned by the https://youzim.it service is bigger than the original website size.

Here's an example with https://www.libraryofjuggling.com as a reference:

```sh
$ # What is the original website size?
$ wget -qr https://www.libraryofjuggling.com/
$ du -sh ./www.libraryofjuggling.com/
182M    www.libraryofjuggling.com/
$
$ # What if we use the zimwriterfs command?
$ zimwriterfs --version
zim-tools 3.1.2

libzim 8.0.1
+ libzstd 1.5.2
+ liblzma 5.2.7
+ libxapian 1.4.20
+ libicu 72.1.0
$ zimwriterfs \
    --welcome="Home.html" \
    --illustration="jugglebanner.jpg" \
    --language="eng" \
    --title="Library of Juggling" \
    --description="An attempt to list all of the popular (and perhaps not so popular) juggling tricks" \
    --creator="libraryofjuggling@gmail.com" \
    --publisher="Kiwix" \
    ./www.libraryofjuggling.com/ ./libraryofjuggling.zim
Resolve redirect
set index
$ du -sh ./libraryofjuggling.zim
178M    ./libraryofjuggling.zim
$
$ # What is the size of the archive I retrieved with the You Zim It service?
$ du -sh ./www.libraryofjuggling.com_5812d0d1.zim
194M    ./www.libraryofjuggling.com_5812d0d1.zim
```

Here's a summary for this website:
| Provenance       | Size (M) |Ratio |
| :--- | ---: |---: |
| Website | 182 | 1 |
| `zimwriterfs` | 178 | 0.97 |
| [You Zim It](https://youzim.it) | 194 | 1.06 |

As you can see, the ratio is not that much of a deal, but what if it happens on some bigger websites?
What may be the cause(s)?
How can I help?

**Comment by rgaudin** [comment]
Those files are actually Google Chrome update data. I could easily reproduce so it's not youzim.it specific.

How did those get in the ZIM? I'm not sure but I believe it's just a matter of how long the crawl lasts for. If the browser has enough time to phone home and download, them you'll find those files in the ZIM as checking other youzim.it files confirms.

If the crawl is too short, you don't get them.

It's possible that some URL triggers it but I don't think so and it's difficult to test (you need a large enough source so it spends enough time but you need to control all URLs as well).

This is clearly not content that we want and we certainly don't want to update chrome inside a running container. I'm opening a ticket upstream but also fixed it on our zimit image in 6324b7c.
