### ISSUE TITLE
Trouble with docker build command

### ISSUE THREAD

**Issue by Clowser323** [openzim/zimit#174]
I use the build command:
`docker build -t openzim/zimit .`

But I get this error and I am not able to find a solution:
https://pastebin.com/P5qDgGqW

**Comment by rgaudin** [comment]
@Clowser323 we don't support aarch64 (you should have mentioned that's your platform!) at the moment because libzim is x86_64 only  but we should *soon*. https://github.com/kiwix/kiwix-build/issues/549
