### ISSUE TITLE
What is the advanage

### ISSUE THREAD

**Issue by billsargent** [openzim/zimit#176]
What is the advantage of using this over a warc file created by webrecorder? This, from what I can tell, is just another version of the crawler. Is there a benefit to it being a zim?

**Comment by kelson42** [comment]
@billsargent It's mostly about the file format. If you want to know why the ZIM format exists and what it does bring, read the official openZIM project wiki at https://openzim.org.

**Comment by rgaudin** [comment]
Indeed the browsertrix-crawler is embedded in zimit and zimit is actually a second pass over the generated warc files.
The goal of zimit is to provide ZIM files from generic websites. browsertrix-crawler is a tool we use to achieve this.

Once transformed into ZIM, it benefits from the xapian full text index and zstd compression but mostly it's usable with a ZIM reader (Kiwix) and can integrate the Kiwix Library.

Note that behavior is very similar as it uses the same _replayer_.

**Comment by billsargent** [comment]
Thank you for the response. I'm going to give it a go. I've messed around with the browsertix-crawler in the past and with the format change  to zim files in your project here, I think that sounds like a great reason to do so.  :)
