### ISSUE TITLE
warc2zim params are stripped to first word

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#18]
When using `--title "Les fondamentaux"` for instance, the actual param sent to `warc2zim` would be `"Les"`.

Concerns all params.

**Comment by ikreymer** [comment]
Hmm, I think this happens due to the command-line first being passed through the bash script.
Can you try encoding the quotes, eg. `--title "\"Les fondamentaux\""`. Does that work, and would that be acceptable workaround?

**Comment by rgaudin** [comment]
Doesn't work, and wouldn't be wanted 🙃

```
Running: warc2zim --url https://isago.ml/ --u https://isago.ml/ --name isago-zimit --tags edm,isago --lang zzz --title i sago go
```

**Comment by rgaudin** [comment]
Also boolean args for warc2zim are passed as `--verbose true` and this become unusable…

**Comment by ikreymer** [comment]
With the fix in the PR, it should now work with double quotes: `--title "'Les fondamentaux'"` or also `--title "Les\ fondamentaux"`. I don't think its possible w/o double quotes unfortunately.

**Comment by rgaudin** [comment]
No, this is not good enough. #26 is another indicator that this is not correctly handled ATM.

**Comment by kelson42** [comment]
I don't really understand the reason why we have this ticket. The user impact sounds benign but this kind of bug is a strong symptom of bad (architectured) command line parsing. Command line parsing has to be done by a dedicated library to provide what the user is in right to expect as "standard" behaviour. The fact that I see javascript code for this purpose on a Python project worries me as well. Why not simply using Python with cutting edge argument parsing library?

**Comment by ikreymer** [comment]
> I don't really understand the reason why we have this ticket. The user impact sounds benign but this kind of bug is a strong symptom of bad (architectured) command line parsing. Command line parsing has to be done by a dedicated library to provide what the user is in right to expect as "standard" behaviour.

The crawling system, in JS, is completely separate from warc2zim, which is in python. The command line for warc2zim have are entirely separate from any crawling options, and my initial suggestion was just to wrap them in `--warc2zim ...` params.
Since this was rejected, the JS needs to be parsing the options, then passing them down to warc2zim.

**Comment by ikreymer** [comment]
It's using a standard library in JS as well for its own params, but it should not have to know all of warc2zim params, so they are just passed as other params in this case.
