### ISSUE TITLE
Handling of external links seems incoherent

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#182]
At https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2023-02/A/mesquartierschinois.wordpress.com/

If I click on the link « deux solitudes », it opens directly the [Wikipedia link](https://en.wikipedia.org/wiki/Template:Chinese_language) in a new tab.

But if I click on « plutot chouette » I get

![IMG_2565](https://user-images.githubusercontent.com/1029718/234793189-851e00fb-2ddf-4497-8afc-0157b1bd38aa.png)

Not sure what shoukd be the correct behaviour, but this seems incoherent.

**Comment by benoit74** [comment]
Issue has changed a bit with Zimit2, where behavior is now coherent so we can probably close this issue. 

There is still one weird thing but for me it is a kiwix-serve bug:
- with https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-05/mesquartierschinois.wordpress.com/ when the target is _blank ("deux solitudes" for instance), then the link is opened both in a new tab and in the current one.
- with https://dev.library.kiwix.org/content/mes-quartiers-chinois_fr_all_2024-05/mesquartierschinois.wordpress.com/ it works as expected.

Shall we close this ticket and open a kiwix-serve issue?

**Comment by rgaudin** [comment]
Yep!

**Comment by benoit74** [comment]
https://github.com/openzim/libzim/issues/887 is opened, closing this one.
