### ISSUE TITLE
Non-clickable link

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#183]
Going to https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2023-02/A/mesquartierschinois.wordpress.com/

At the end of the page I get
![IMG_2566](https://user-images.githubusercontent.com/1029718/234792971-3094dd75-cafc-4829-b75f-c1ca93bf72c6.png)

I can not click on « laisser un commentaire », only the last one, all th other seem to work.

**Comment by rgaudin** [comment]
Looking at the screenshot, it looks like you're on the USA tag… this is not reflected in the URL !!

I've clicked all the “laisser un commentaire” link and all of them work for me on Firefox. It takes me to the bottom of the article's page, where there's a comment field.
