### ISSUE TITLE
NDLA recipe failed

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#184]
NDLA recipe failed
https://farm.openzim.org/recipes/ndla_nno_all

Command Log: docker run -v /my-path:/output:rw --name zimit_ndla_nno_all --detach --cpu-shares 3072 --memory-swappiness 0 --memory 2147483648 --shm-size 1073741824 ghcr.io/openzim/zimit:1.12.1 zimit --url="https://ndla.no/" --name="ndla_nno_all" --lang="nno" --title="Norwegian Digital Learning Arena" --description="NDLA is a Norwegian joint county enterprise offering open digital learning assets for upper secondary education." --exclude="https://ndla.no/subject:20 " --favicon="https://ndla.no/static/ndla-favicon.png" --output="/output" --statsFilename="/output/task_progress.json" --adminEmail="contact+zimfarm@kiwix.org"

Offliner Log: zimit --url="https://ndla.no/" --name="ndla_nno_all" --lang="nno" --title="Norwegian Digital Learning Arena" --description="NDLA is a Norwegian joint county enterprise offering open digital learning assets for upper secondary education." --exclude="https://ndla.no/subject:20 " --favicon="https://ndla.no/static/ndla-favicon.png" --output="/output" --statsFilename="/output/task_progress.json" --adminEmail="contact+zimfarm@kiwix.org"

**Comment by rgaudin** [comment]
Recipe tries to use version `1.12.1` which doesn't exist. Not sure how you could get that; maybe by cloning a non-zimit recipe? I changed it to `:dev`.

FYI recipe name, `Name` and thus filename as well as `Description` are incorrect.
