### ISSUE TITLE
Frequent initial connect timeouts

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#185]
We frequently get timeouts on our initial request to the main URL in the python code that ensures the main URL is reachable

https://github.com/openzim/zimit/blob/fc9ad3759e62783420da2d577ae30721e8aaa64b/zimit.py#L422-L430

I just encountered it while running the tests. Happened a few successive times then disappeared

```
failed to connect to http://isago.rskg.org/: HTTPConnectionPool(host='isago.rskg.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd6197cac50>, 'Connection to isago.rskg.org timed out. (connect timeout=12.2)'))
```

This means that after `12.2` seconds, the `connect()` call to socket didn't receive any byte.
Kinda hard to believe as the website was online and the network was on.

We've already played a bit with that timeout ; maybe we should just retry the whole thing twice.

**Comment by benoit74** [comment]
I also encountered small variations of this issue. Not sure it is linked, but at least it is the same code which fails. And in all those cases, the website is online when I test it from my machine.

Both for http://www.urbandictionary.com and https://www.menzis.nl/premie-berekenen-en-aanvragen/:
```
failed to connect to http://www.urbandictionary.com: Exceeded 30 redirects.
```
and
```
failed to connect to http://empepa.net/category/arktida/: HTTPConnectionPool(host='empepa.net', port=80): Max retries exceeded with url: /category/arktida/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fbac40ab760>: Failed to resolve 'empepa.net' ([Errno -2] Name or service not known)"))
```
and
```
failed to connect to https://www.menzis.nl/premie-berekenen-en-aanvragen: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
and (both for www.conservapedia.com and www.goat.cz)
```
failed to connect to https://www.conservapedia.com: HTTPSConnectionPool(host='www.conservapedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2f7388f670>, 'Connection to www.conservapedia.com timed out. (connect timeout=12.2)'))
```

**Comment by benoit74** [comment]
This does not exists anymore in Zimit 2
