### ISSUE TITLE
New zim should not be defaulted to English

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#186]
When creating a zim file via zimit the language spec is by default set to English.

It should per default (so without user specification) set to the language(s) of the scraped Web pages.

**Comment by rgaudin** [comment]
That's the current behavior. If you don't specify a language, it uses the `<html lang=` param value… and then defaults to `eng` in last resort.

I think this serves the feature request correctly. Maybe zimfarm's param description could be improved.

**Comment by kelson42** [comment]
@rgaudin Can we fix the help then on zouzim.it? Here is what is written: "ISO-639-3 (3 chars) language code of content. Defaults to `eng`" online.

**Comment by rgaudin** [comment]
That's what I meant ; it's the zimfarm's offliner description that's being used there.

**Comment by kelson42** [comment]
Ok, we need to fix that sentence. What about if content is in many languages? The languages are retrieved in each html page or only the first page?

**Comment by rgaudin** [comment]
Only the homepage

**Comment by kelson42** [comment]
OK, thx for explanations. I will treat the ticket a bit later.

**Comment by kelson42** [comment]
I have open https://github.com/openzim/zimit/issues/187 and https://github.com/openzim/zimfarm/issues/771. Closing.
