### ISSUE TITLE
URL should be adjusted for warc2zim

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#19]
When using an URL such as `https://isago.ml`, zimit is happy and captures it but `warc2zim` is not as it can't find such a URL in WARC files. Obviously, the actual URL in WARC is `https://isago.ml/` (trailing slash).

We cannot fail after capture on such scenario. We could either fail early (I don't recommend) or be smarter and just append the trailing slash to the `warc2zim` argument if it's missing.

**Comment by ikreymer** [comment]
Ah yes, the dreaded trailing slash issue.. I think i encountered this multiple times in different scenarios.. Agree it should just check the URL and add the slash.
