### ISSUE TITLE
MIT OpenCources Recipe issue

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#192]
I've created this recipe
https://farm.openzim.org/recipes/mitopencourse_en_all

But it's not being created

Command:
docker run -v /my-path:/output:rw --name zimit_mitopencourse_en_all --detach --cpu-shares 3072 --memory-swappiness 0 --memory 3221225472 --shm-size 3221225472 ghcr.io/openzim/zimit:dev zimit --adminEmail="contact+zimfarm@kiwix.org" --description="Free lecture notes, exams, and videos from MIT." --favicon="https://user-images.githubusercontent.com/71325886/237537094-9e977e37-7a8b-4695-b5c0-c6d4df9774b6.png" --lang="eng" --name="mitopencourse_en_all" --output="/output" --statsFilename="/output/task_progress.json" --title="MIT Open Course Ware" --url="https://ocw.mit.edu" --verbose --workers="6"

Offliner Command:
zimit --adminEmail="contact+zimfarm@kiwix.org" --description="Free lecture notes, exams, and videos from MIT." --favicon="https://user-images.githubusercontent.com/71325886/237537094-9e977e37-7a8b-4695-b5c0-c6d4df9774b6.png" --lang="eng" --name="mitopencourse_en_all" --output="/output" --statsFilename="/output/task_progress.json" --title="MIT Open Course Ware" --url="https://ocw.mit.edu" --verbose --workers="6"

**Comment by kelson42** [comment]
@RavanJAltaie !?! It's running https://farm.openzim.org/pipeline/8e688d38-de31-4f5e-9f5d-642957a4c2c8
