### ISSUE TITLE
zim do not open in the Firefox ESR browser using the Kiwix extension: offline wikipedia reader 

### ISSUE THREAD

**Issue by Katran-399A** [openzim/zimit#195]
Hello.
The received files (https://youzim.it/), for example, https://s3.us-west-1.wasabisys.com/org-kiwix-zimit/other/www.cqham.ru_80a5c4f0.zim
do not open in the Firefox ESR 52.9.0 (x32) browser using the Kiwix extension : offline wikipedia reader 3.9.0 (https://addons.mozilla.org/ru/firefox/addon/kiwix-offline/versions /).
At the same time, the files from here: https://library.kiwix.org / open normally.
Tell me how to fix this error.
I didn't fill in the advanced options section https://youzim.it/ (I left everything by default).
Maybe you need to set some settings in the advanced options section https://youzim.it/?
If so, which ones exactly?
Thank you.

**Comment by kelson42** [comment]
@jaifroid Is this the expected behaviour?

**Comment by f0sh** [comment]
I can confirm this; Using the Edge Browser Extension and a zim archive generated with the zimit docker container fails with the following error:

```
Unsupported archive type!
You are attempting to open a Zimit-style archive, which is currently unsupported in this app.
There is experimental support for this kind of archive in the Kiwix JS PWA. Go to: https://pwa.kiwix.org/.
Alternatively, you can use Kiwix Serve to serve this archive to your browser from localhost. Kiwix Serve is included with Kiwix Desktop
```

Whilte the extension does not work, the error describes using `kiwix-serve` should work, which indeed does!

**Setup**
  - openzim/zimit@v1.3.1
  - Edge Version 114.0.1823.43 (64-Bit)
  - Kiwix Extension v3.9.0

The generation of the zim file worked without errors.

```
$ podman run -v /output:/output --rm -it --shm-size=1gb ghcr.io/openzim/zimit zimit --url https://go.dev/doc/ --name "go-docs" --workers 3 --waitUntil domcontentloaded
Processing 15 WARC files to ZIM
Resolve redirect
set index
```

**Comment by Jaifroid** [comment]
@Katran-399A Indeed, as @f0sh says, Zimit-based archives do not currently work in the browser-extension version. You have two options:

* Use Kiwix-serve (this could be the version that is provided in Kiwix Desktop);
* Try the experimental Zimit support in https://pwa.kiwix.org (in Firefox, you can bookmark this, and it will work offline; in Chrome or Edge you can Install it as an offline-first app).

This is related to https://github.com/kiwix/kiwix-js/issues/1009.

**Comment by f0sh** [comment]
Thanks for clarifying. I think that helps a lot.
I did not try it yet, but are Zimit generated Archives acompatible with the Android / iOS apps?

Is there anywhere a guide on how to create zim archives which can be used together with the browser extension?

**Comment by Jaifroid** [comment]
Zimit-generated archives are compatible with the Android app. They are not compatible with the dedicated iOS app, but you can install the PWA (https://pwa.kiwix.org) on iOS by adding it to your Home screen in Safari. It will then act like an installed app, has its own icon on the Home screen, etc. This version is (experimentally) compatible with most Zimit archives, though not 100% guaranteed!

The browser extensions: we are looking in to adding Zimit support to them. It will probably take a few months. Alternatively, try the PWA which is based on the same code as the browser extensions, but with added features.

You can't create your own non-Zimit ZIM archives without a lot of technical knowledge, and in particular the site would need to be compatible with one of our standard scrapers such as mwOffliner. If it's a MediaWiki-compatible site, it might be possible to do it, but it would need a lot of work.
