### ISSUE TITLE
Upgrade python-scraperlib to 3.x, including CLI support for description / long_description flags

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#202]
See https://github.com/openzim/overview/issues/21

**Comment by rgaudin** [comment]
Not a valid requests, zimit had those since 1.4.0 (3w old)

**Comment by benoit74** [comment]
@rgaudin I'm sorry, but I struggle to find how you set a long description with `zimit`

**Comment by rgaudin** [comment]
You're right `--long-description` is not passed to warc2zim. It's an easy fix. Do you want to do it? We'd need to update the ZF offliner as well so it's available everywhere

**Comment by rgaudin** [comment]
Fixed
