### ISSUE TITLE
Youzimit job had to be canceled after 7 days of operation

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#205]
I had to cancel https://farm.youzim.it/pipeline/7023934f-acfa-4d59-9887-933eddd2095d which was running for 7 days and reducing youzimit processing capability.

**Comment by benoit74** [comment]
Solved upstream by https://github.com/openzim/zimit/issues/204

**Comment by benoit74** [comment]
@kelson42 do you expect something specific to be done on this? With @rgaudin we consider this issue as solved by the upstream fix + the release of 1.4.1

**Comment by kelson42** [comment]
> With @rgaudin we consider this issue as solved by the upstream fix + the release of 1.4.1

Me too, this is why I closed it. I assigned it to you, because you handle it.
