### ISSUE TITLE
Scraper is stuck on `athena18` and not on `michael_blob`

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#210]
Some tasks on https://farm.openzim.org/recipes/dp.la_en_all never finished, they got stuck in the middle of the scraping. 

At the same time, other tasks with same Docker images, same settings succeeded to complete.

The difference seems to be the worker, the 2 tasks than ran on `athena18` got stuck while the last 4 tasks than ran on `michael_blob` achieves to complete.

Do we have any idea about how to investigate further such issues?

**Comment by rgaudin** [comment]
- [`#60fae`](https://farm.openzim.org/pipeline/60faed9f-264a-490c-9919-e33b96637623) was started on July 27 and stopped updating the day after. It never failed and was canceled a month after
- [`#a6d21`](https://farm.openzim.org/pipeline/a6d210c8-6d3b-4548-bd48-7954e2747253) was started on **August 27** and was canceled after closed to 11h. There are logs indicating progress up to the time of cancellation so **this one wasn't stuck**.

This leaves us with a single occurrence… on a task that was running on `:dev` prior to the `1.5` fixes that came from upstream which should fix similar problems.

**Comment by benoit74** [comment]
Oups, you are right, I did not realized `#a6d21` was still running.
