### ISSUE TITLE
Crawler statistics are not available anymore

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#213]
Due to an upstream change (https://github.com/webrecorder/browsertrix-crawler/issues/358), browsertricks statistics are output only at the end of the crawl. 

This is an issue since it prevents us to report scrapping progress appropriately.

Nota: it looks like format was not changed, but we have to be careful about it before closing this issue once a solution has been provided upstream

**Comment by rgaudin** [comment]
Ah! it was an upstream change.

**Comment by benoit74** [comment]
PR ready: https://github.com/webrecorder/browsertrix-crawler/pull/374

**Comment by benoit74** [comment]
Fixed in Browsertrix Crawler 0.11.0 and hence zimit 1.5.1
