### ISSUE TITLE
500 error on certain settings

### ISSUE THREAD

**Issue by ikreymer** [openzim/zimit#216]
Based on the info in https://github.com/openzim/zimit/issues/190#issuecomment-1709709465, youzim.it does return a 500 error.
Was able to repro this earlier: (It should of course been opened as a new issue)

<img width="1175" alt="Screenshot 2023-09-07 at 10 51 09 AM" src="https://github.com/openzim/zimit/assets/1015759/fac6b18c-743d-4039-938f-25a3a50c08d1">

Happened when entering lang 'eng', custom title, and custom sizeLimit. When refreshing and entering no default settings, the request succeeded.

**Comment by rgaudin** [comment]
Ah thanks! I could not repro and the target website generated an HTTP 500 during the crawl. Given the feedback was odd, I didn't dig further.

I'll investigate

**Comment by rgaudin** [comment]
OK, it was a bug affecting users wanting to manually set timeLimit or sizeLimit. Fixed in https://github.com/openzim/zimit-frontend/commit/7934fc92736d0e4c0303fb990a50df5d1c32550f
