### ISSUE TITLE
Docker volume permission

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#22]
Marking this as a bug although it's debatable :)

Since zimit drops to userland in its run script, both the node code and warc2zim are run in userspace. It means that with the current configuration of having `/output` mapped to the docker volume and using `--output=/output`, `zimit` user usually have no rights to create a file or folder inside `/output`.

This is worked around for nodejs by creating a temp folder and changing its ownership before switching user but doesn't apply to warc2zim.

We could either duplicate node behavior (create a `/output/zim/` folder and owning it as zimit) or run as root but I think we cannot assume `/output` will be writable by `zimit` user.

**Comment by ikreymer** [comment]
Hm, I worked around this by setting the permissions of the directory outside of Docker to write all. Is that not possible, or doesn't work in your setup?
Let me see if there's another way..

**Comment by ikreymer** [comment]
I think a simpler solution that seems to work is just to add:

```
chmod a+w $output_dir
```

in the run.sh -- that should ensure the dir is writable if possible.

**Comment by rgaudin** [comment]
Works for me
