### ISSUE TITLE
Questionsexualite recipe is failing

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#221]
This recipe is failing 
https://farm.openzim.org/recipes/questionsexualite_fr_all

I tried to understand why? All what I found is: Exiting with error code 100 which I don't know what does it mean.
Please check.

**Comment by rgaudin** [comment]
zimfarm says it suceeded

**Comment by kelson42** [comment]
we need links to task to secure we all talk about the same stuff

**Comment by benoit74** [comment]
Missing info + no issue so far from my PoV, I close it for now, feel free to reopen if needed.
