### ISSUE TITLE
Pass same User-Agent to check_url and crawler

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#227]
As of today, at startup zimit is:
- checking the URL with check_url, which uses Python requests
  - no useragent is specified, so default one is used, e.g. `python-requests/2.31.0`
- starting browsertrix crawler
  - either browsertrix default user agent or the one specified to zimit through CLI flags is used

In all cases, the target server is hence receiving two requests from the same IP in few seconds from two different user agents. 

This is not a good thing, and might even be the cause of #224.

We should use the same User-Agent for both situations.

**Comment by rgaudin** [comment]
> In all cases, the target server is hence receiving two requests from the same IP in few seconds from two different user agents.
> 
> This is not a good thing, and might even be the cause of #224.

That's very unlikely. This is an isolated **single HEAD request** that happens prior to the crawler staring and then emitting as much requests as it can, using an odd User-Agent.
Keep in mind that an enormous share of Internet users use a shared IP address with their colleagues, household, or ther devices (phone), etc. I'd eat my arm if it was the reason for #224 😅
 
> We should use the same User-Agent for both situations.

Absolutely.

**Comment by benoit74** [comment]
I hope you are hungry, because I reproduced the issue 🤣

```
>>> import requests
>>> resp = requests.get("https://www.eatingwell.com/")
>>> resp.status_code
406
```

And then from this point, any requests (curl, python, whatever) from the same machine (IP, I imagine) fails with 405 errors.

From a different machine:
```
>>> import requests
>>> resp = requests.get("https://www.eatingwell.com/", headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"})
>>> resp.status_code
200
>>> resp = requests.head("https://www.eatingwell.com/", headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"})
>>> resp.status_code
200
```

Tada ... (yes, I hate this behavior, but I suspect this might even be the root cause of some situations of #185)

**Comment by rgaudin** [comment]
😨 Not so fast, the problem is not the one I quoted (ie. different UA from same IP) but the fact that any request with a `python-requests/` prefixed UA blacklists the IP for some time 

```py
In [1]: import requests
   ...: resp = requests.head("https://www.eatingwell.com/", headers={"User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"})
   ...: print(resp.status_code)
   ...: resp = requests.get("https://www.eatingwell.com/", headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0"})
   ...: print(resp.status_code)
200
200

In [2]:
```

**Comment by benoit74** [comment]
You are right, sorry 😉

But this still needs to be fixed, and this is still very aggressive (I now know how to prevent a whole company/campus from accessing some websites, just do one HEAD request with `python-requests` UA from their public web browsing IP ...)

**Comment by rgaudin** [comment]
Yes, it's terrible.
