### ISSUE TITLE
Use our own default User-Agent

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#228]
By default, when no User-Agent is specified to zimit, no User-Agent is specified to browsertrix crawler and default one is hence used. Only a User-Agent suffix is passed (and hence appended by browsertrix) to 

The problem with this is that:
- we never know which User-Agent value is used in the end, it is not logged
- we have too little control on this User-Agent, there is always a risk it might get broken at some point by a release

We think we should specify our own default User-Agent and pass it to browsertrix in all cases, to ensure reproducible / consistent behaviors.

This is also probably a mandatory change for #227 (or at least it makes it way easier to solve)

**Comment by rgaudin** [comment]
Also, browertrix's _device_ param implies a change to it but the choice is very limited and resulting UA does not look like a regular internet user.

Primary goal of this should be to _impersonate_ a regular user, as to be less sensible to Captchas and other blocking services
