### ISSUE TITLE
Default rules to avoid crawler traps

### ISSUE THREAD

**Issue by ikreymer** [openzim/zimit#23]
Many sites include search, or sort options that can result in 'crawler traps'. Some common ways to avoid this is by specifying regexes to exclude, eg. `--exclude "\"\?q=\""`
 
Add a list of default patterns to be excluded to avoid having to specify for every site..

**Comment by rgaudin** [comment]
Think we can close this one as we haven't seen much need for that (we're setting those in recipes for now)

**Comment by ikreymer** [comment]
Adding details: For now, the per recipe exclude rules added seem sufficient. Don't have enough info yet to add default rules for all sites, and `q=` can be added explicitly as needed.
