### ISSUE TITLE
`check_url` should do a GET instead of HEAD

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#230]
Currently `check_url` is doing a HEAD request.
Unfortunately, not all servers have implemented this verb (since it is not mandatory).
We should do a GET request and stop after first bytes received.

**Comment by benoit74** [comment]
NOTA: I'm not sure this is trivial, even with `stream=True`, I'm not sure what really happens

**Comment by benoit74** [comment]
It is almost trivial (and should even be fixed since we use `stream=True` but never close the request, so connection is staying opened):
https://docs.python-requests.org/en/latest/user/advanced/#body-content-workflow

![image](https://github.com/openzim/zimit/assets/7102089/727f3d69-8b66-464d-ab0e-8a1ae61b1c2f)

**Comment by rgaudin** [comment]
Yep ; we just need to close the connection.
