### ISSUE TITLE
Add a `--version` command

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#234]
Allow to display zimit version with `zimit --version` ; this should also display version of warc2zim and browsertrix crawler.

**Comment by kelson42** [comment]
Sounds mandatory. Not sure if this is already made, but at starts of scrape, clearly writing in the log the version of the scraper is often pretty usefuly as well. Considering that for Zimit, we use intensively the `dev` version, writting the version of the dependences at start as well would probably be helpful.

**Comment by Syoinn** [comment]
Hello! I'm trying to work on this function. But I need advice on a couple of points:

1. Should I add environment variables to the Dockerfile or hardcode the versions in zimit.py? Am I on the right track?
2. You mentioned the log, but I didn't find the related module in the source code. Am I expected to integrate a logging module as part of this issue?

I am a newcomer and I wanna make sure I understand the issue correctly. Your advice would be very helpful.

**Comment by benoit74** [comment]
@Syoinn sorry, this has already been solved by https://github.com/openzim/zimit/pull/272, we've forgot to mention it over there and close this issue
