### ISSUE TITLE
Improve out-of-scope error messages

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#242]
Currently when zimit runs on a website and a link, for some (or any reason) is out of scope for the run, users subsequently trying to click on that link will end up seeing a rather absconse `Sorry, the url https://www.foobar.url is not found on this server` error message
![Capture d’écran 2023-11-13 à 15 19 41](https://github.com/openzim/zimit/assets/21675885/50122062-b669-4b08-a1a7-279810bf501b|width=100)

This is not really helpful to the user as it does not explain whether this is a bug or a feature.

A clearer message, indicating something along the lines of "This pages was not archived as its content was outside of the range of pages crawled. Sorry!" might be somewhat more helpful / less frustrating.

We do have friendly illustrations at hand that we could also use:

![Error 404](https://github.com/openzim/zimit/assets/21675885/90e92e23-2f88-446e-a4cb-ec2468d767d3|width=50)
or
![Dead-Kiwix](https://github.com/openzim/zimit/assets/21675885/6cb2935b-cf32-4ffd-a8ca-01d27eaebdbd|width=50)

**Comment by benoit74** [comment]
This error message does not exists anymore with Zimit2
