### ISSUE TITLE
Documentation states incorrectly that Zimit is running a headless-Chrome

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#248]
Main README.md states that "This version of Zimit runs a single-site **headless-Chrome** based crawl in a Docker container and produces a ZIM of the crawled content."

This is wrong AFAIK because:
- the `--headless` parameter is not passed to crawler, so crawler is running in headfull mode
- since crawler 0.12.2, it is not running Chrome/Chromium anymore but Brave (see https://github.com/webrecorder/browsertrix-crawler/releases/tag/v0.12.0 and also https://github.com/webrecorder/browsertrix-crawler/issues/441)

@rgaudin do you confirm?

**Comment by rgaudin** [comment]
There's no X server so it is headless but indeed the underlying browser changed. Do you think it's important for our user and should be changed or should we just say it runs a browser?

**Comment by benoit74** [comment]
We could just say that it runs Browsertrix Crawler, so that the users might hand over to the crawler documentation for details, hence our documentation will always be accurate (details about the browser and puppeteer are not something managed by us anyway).

**Comment by benoit74** [comment]
> There's no X server so it is headless. 
From my understanding, even if there is no X server, the browser is nevertheless started in headful mode. This is why there is a `--headless` parameter in Browsertrix to started the browser in headless mode. Browsertrix crawler is always running in Docker so without X server AFAIK. Did I missed something?

**Comment by rgaudin** [comment]
No, I don't think this sentence was written in a chrome-option-aware technical way. I think it meant that it's not user-interactive and not visible. The rest is chrome-internals that might be of interest for some advanced usage.
Rewrite as you see fits.
