### ISSUE TITLE
Removing search bar from harmony project zim file

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#259]
The harmony project file in library has a search bar, please help in what should I change in recipe to remove it from the resulted file?
the recipe is [here](https://farm.openzim.org/recipes/harmony-project.org_en_all).

**Comment by benoit74** [comment]
I'm waiting for ZIM to be correct first.

**Comment by RavanJAltaie** [comment]
So as per the update [here](https://github.com/openzim/zimit/issues/258), we should wait for zim update then we will look to fixing the search bar?

**Comment by benoit74** [comment]
Yes, no need to do this if we finally never achieve to have a working ZIM (even if I have good hopes), plus the site might change in between and break the customization to remove the search bar, so it is way better to wait.

**Comment by Jaifroid** [comment]
ZIM isn't broken. As mentioned in #258, there is an issue with screen resolution in this ZIM. Images (at least), and possibly also CSS, have been scraped only at the resolution of the scraper, whatever that is. It has defaulted to mobile, as can clearly be seen, e.g. in Kiwix JS Browser extension, if you change the screen size to mobile and go to the home page -- many more images show than in desktop resolution, where the big-format ones are pretty much all missing. Conversely, the small thumbnails for the sheet music are missing in mobile format and showing in desktop.
