### ISSUE TITLE
[doc] ghcr.io URL in repo's About section

### ISSUE THREAD

**Issue by bwenrich** [openzim/zimit#260]
The Github repo description currently contains a dead link to https://hub.docker.com/r/openzim/zimit
![image](https://github.com/openzim/zimit/assets/27692895/88ea1cd0-1cd3-4f79-bb84-7ac178437417)

Due to the ghcr.io migration, I think this should be updated to `ghcr.io/openzim/zimit` or `https://github.com/openzim/zimit/pkgs/container/zimit`

**Comment by benoit74** [comment]
@kelson42 @rgaudin what do we want to use as a link on each scrapers repo?

- On some scrapers we have a link to download.kiwix.org, e.g. [download.kiwix.org/zim/gutenberg](https://download.kiwix.org/zim/gutenberg) on [gutenberg](https://github.com/openzim/gutenberg)
- On [mwoffliner](https://github.com/openzim/mwoffliner/ ) we have a link to https://www.npmjs.com/package/mwoffliner

**Comment by rgaudin** [comment]
It's an interesting question. I think there are two questions to answer here:

- What links to include in the README (our main source of info)
- What link (singular) to set as a repo link (appears on top-right in Github) **if any**.

I'd say:

- link to docker image (on ghcr.io) as prod is docker first and that saves a lot of support troubles.
- link to the package manager (pypi, npm) if it exists.
- I'm fine with no repo link or linking to a kiwix.org page or wiki page that describe what scrapers are and why we have them.

Links to ZIM are a bad idea IMO. That's not what the scrapers are for and if one finds the scraper and can't find the openZIM produced ZIMs, he's probably heading towards difficulties.

**Comment by benoit74** [comment]
Links to docker and Pypi are already including with the badges in Python scrapers (if they obey the Python bootstrap).

Question is hence more about the repo link itself

**Comment by benoit74** [comment]
Removed wrong link until a real decision is taken
