### ISSUE TITLE
Upgrade to browsertrix crawler 1.0.0 beta

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#284]
Should we upgrade to browsertrix crawler 1.0.0 which is still in beta? 

It prove to solve at least some issues of https://github.com/openzim/zim-requests/issues/830

I was reluctant to mix this significant change (recording mechanism is completely rewritten) with our own big changes, but it has been in beta since November now, and every new beta version bring only small fixes / enhancements, i.e. the beta seems to be working pretty well.

And if it could solve some (many?) scraping issues ... (https://github.com/openzim/zimit/issues/283 and https://github.com/openzim/zimit/issues/266 might be impacted as well).

**Comment by Jaifroid** [comment]
Worth a try? Can you do any test runs with it to see if it does improve stability before committing anything?

**Comment by benoit74** [comment]
As I said, I ran one test locally and it solved first issues of https://github.com/openzim/zim-requests/issues/830

I also ran another test on a random small website and ZIM produced was OK (but site is so small ... it means little)

I could run a full test on one of our test recipes for zimit2 if it is necessary to take a decision.

I don't consider it would help me to decide, my concern is more than once update is done, I will always have in the back of my mind for every warc2zim2 issues "is this a real issue of warc2zim2 or is it linked to browsertrix 1.0.0".

Given recent comments from Ilya (regarding the fact that we might get access to more information with 1.0.0 thanks to new capture architecture), and given we will have to do the move at some point anyway, I suggest to do the update now.

If no-one (@kelson42 @rgaudin @mgautierfr) disagree before next Monday, I will do the update on Monday.

**Comment by rgaudin** [comment]
I am in favor of updating.

**Comment by ikreymer** [comment]
Thank you for testing! Yes, we would also be curious to know if the 1.0.0 beta version is more stable for zimit, as we prepare to release 1.0.0. In particular, also hoping it would address page crashes like in #266. Let us know how it goes!

**Comment by kelson42** [comment]
https://github.com/openzim/warc2zim/issues/140 is also ultimately concerned here as well

**Comment by Jaifroid** [comment]
Looks like this was fixed in #285 and should be closed?

**Comment by benoit74** [comment]
Yep, thank you
