### ISSUE TITLE
Add option to only crawl website and not run warc2zim conversion

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit#297]
For debugging purpose, it might be useful to only run the crawling and not run warc2zim conversion (which might be known to fail, or even hang forever in a dead loop).

We should add a `--crawl-only` CLI argument to support this scenario (and integrate this in the Zimfarm obviously).

**Comment by rgaudin** [comment]
PR looks good but I'm not sure about the operational value of this

> which might be known to fail

How is that a problem if we can keep the WARCs (and even upload them via Zimfarm)? warc2zim is a speedy process

> or even hang forever in a dead loop

Is this an existing problem? Where's the ticket about this? https://github.com/openzim/warc2zim/issues/132 is zimit1 AFAIK

**Comment by benoit74** [comment]
> How is that a problem if we can keep the WARCs (and even upload them via Zimfarm)? warc2zim is a speedy process

Speedy compared to the crawl, yes. But still time consuming for probably nothing.

> Is this an existing problem? 

It happened to me during development on my machine, I don't see why it would not happen during production. And I most probably have a case this morning but still did not had time to collect material to open corresponding issue.

**Comment by benoit74** [comment]
https://github.com/openzim/warc2zim/issues/246

**Comment by benoit74** [comment]
But you're right that from an operational point of view, it would make more sense to adapt Zimfarm worker so that logs and artifacts are uploaded even when a cancellation is requested. It would probably help in multiple cases.

**Comment by rgaudin** [comment]
Yes, it's a huge frustration point for most scrapers

**Comment by benoit74** [comment]
Then, let's close this in favor of https://github.com/openzim/zimfarm/issues/965
