### ISSUE TITLE
Many pages on `getbootstrap.com_en_all_2024-05` have erroneously exposed JavaScript (as visible text) appearing on the bottom of the page

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimit#306]
I suppose we won't fix any Zimit 1 scrapes (this is Zimit 1), but it might be useful to compare with a Zimit 2 scrape of the same, to determine if the issue is in scraping process or in warc2zim. For examples, see:

https://library.kiwix.org/content/getbootstrap.com_en_all_2024-05/A/getbootstrap.com/docs/5.3/getting-started/webpack/

https://library.kiwix.org/content/getbootstrap.com_en_all_2024-05/A/getbootstrap.com/docs/5.3/getting-started/javascript/

And scroll to very bottom of page in each instance. In both Kiwix Serve and Kiwix PWA we see lots of exposed JS like in the screenshot below. On the original Web pages, this text is not present.

![image](https://github.com/openzim/zimit/assets/4304337/26372141-e79e-4ce5-b178-02339f97c38e)

**Comment by benoit74** [comment]
Thank you for reporting this! After a small test, I confirm this is a Zimit1 issue, and that this issue is solved with Zimit2.

I will hence close this issue since it is already fixed, but glad to know we fixed this as well (and better safe than sorry)
