### ISSUE TITLE
Lots of duplicated content

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#31]
Most ZIMs created with zimit raise **a lot** of errors from zimcheck due to duplicate content. For some like journals.openeditions, it generates a 1.4GB large zimcheck log…

Taking a quick look at those logs, I've identified several common scenarios:

## Ads

URLs that return nothing or close to nothing are likely to clash with each other. It's clearly visible for ad-related requests with are mostly unique due to tracking IDs but don't serve any content

```
stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j86&tid=UA-605379-1&cid=1706321979.1602606428&jid=1297879906&gjid=1029232721&_gid=1576942764.1602606428&_u=YGBAgEABAAAAAE~&z=1259133512 (idx 430) and stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j86&tid=UA-605379-5&cid=1706321979.1602606428&jid=1274727808&gjid=439935886&_gid=1576942764.1602606428&_u=YGDAgEABAAAAAE~&z=1784451389 (idx 435)
```

The content of those 2 URLs is `1`. In this ZIM, there are about a thousand occurrences of those.

Another example, is with google analytics

```
www.google-analytics.com/collect?v=1&_v=j86&a=1124483121&t=pageview&_s=1&dl=https%3A%2F%2Fedu.gcfglobal.org%2Fen%2Ftopics%2Fmath%2F&dp=%2Fen%2Ftopics%2Fmath%2F&ul=en-us&de=UTF-8&dt=Free%20Math%20Tutorials%20at%20GCFGlobal&sd=24-bit&sr=800x600&vp=800x600&je=0&_u=QCCAgEAB~&jid=1596307224&gjid=5366868&cid=1706321979.1602606428&tid=UA-605379-5&_gid=1576942764.1602606428&z=1957848174 (idx 470) and www.google-analytics.com/collect?v=1&_v=j86&a=1747573734&t=pageview&_s=1&dl=https%3A%2F%2Fedu.gcfglobal.org%2Fen%2Ftopics%2Foffice2000%2F&dp=%2Fen%2Ftopics%2Foffice2000%2F&ul=en-us&de=UTF-8&dt=Free%20Office%202000%20Tutorials%20at%20GCFGlobal&sd=24-bit&sr=800x600&vp=800x600&je=0&_u=QCCAgEAB~&jid=264127233&gjid=379906133&cid=1706321979.1602606428&tid=UA-605379-5&_gid=1576942764.1602606428&z=552815020 (idx 485)
```

This is a small GIF image.

Ads being useless everywhere we could consider using blacklists from adblock to filter those out.

## Actual duplicates

```
edu.gcfglobal.org/en/topics/computers/images/social/facebook_icon.svg (idx 55) and edu.gcfglobal.org/en/topics/word/images/social/facebook_icon.svg (idx 343)
```

In this example, the source website duplicates the same content (happens on all the social media logos) at different locations.
One clue from our side is that they have identical Etags.

Note: there might be *legit* (actually the opposite) duplicates in those zim files but it would be hidden by this ocean of meaningless ones.

## Question

@kelson42 should we do anything about those at this point? Identifying duplicates on dynamic content is a complicated cross-scraper topic.
As per ads-related duplicates, I think that's something we could do in the future. Should I open a ticket?

**Comment by ikreymer** [comment]
This was the reason for initial filtering out URLs like this, unless the `-a` flag is used. Could support an exclude rule for google analytics and other common domains. By duplicates, you mean the content is duplicate, not the URL, as that's not possible with ZIM?  WARCs have a way of pointing to a duplicate content with a different URL, I suppose there's not a way to do that with ZIM? Of course, there's no way to generally avoid duplicate content at different URLs, so it should not be treated as an error in this case.

**Comment by ikreymer** [comment]
Probably the simplest solution would just be to filter out URLs like `*.doubleclick.net/` and `google-analytics.com/` in warc2zim.

**Comment by rgaudin** [comment]
@ikreymer, yes

- we could filter those domains
- this should be a warning (fixed in master zim-tools but not released)
- we have RedirectArticle for that purpose ; the difficulty is knowing which is a duplicate of which (implies checking)

I'll open a ticket for the block domains list in warc2zim.

**Comment by kelson42** [comment]
Any reason to not consider this ticket as a duplicate of https://github.com/openzim/warc2zim/issues/63?

**Comment by rgaudin** [comment]
It's not the same thing but given the very minimal actual impact of this and the fact that the 63 ticket will greatly reduce it, it's not worth additional effort at this stage.
