### ISSUE TITLE
after createing a webiste clone ??? 

### ISSUE THREAD

**Issue by spydaz** [openzim/zimit#317]
the app has made a few zimmit files for me ... but i cannot seem to get them to display they content ...

Error
The requested URL can not be loaded because service workers are not supported here.

If you use Firefox in Private Mode, try regular mode instead.

If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost.

is this a browser issue ? how can this be resolved ? is it a certificate problem ?
this has happened with every file made on the website ?

**Comment by benoit74** [comment]
This is a known Zimit1 issue. ZIMs created with Zimit v1 are relying on a Service Worker and must hence be served on a valid HTTPS connection (including valid TLS certificates).

Zimit2 has now been released last week and will soon be deployed on zimit.kiwix.org. Zimit v2 does not use anymore a Service Worker and can be loaded in all readers without restrictions, even HTTP will work.

You will have to either setup a valid HTTPS connection with valid TLS certificates, or recreate the ZIM once Zimit v2 is deployed.
