### ISSUE TITLE
Through zimit I created a zim of forums.gentoo.org but looks like not everything is packaged? Browser extension wants to open internal link as external :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [openzim/zimit#321]
![image](https://github.com/openzim/zimit/assets/3514015/a718794f-759b-480e-b30d-52172ab10430)

**Comment by benoit74** [comment]
Did you created this ZIM through zimit.kiwix.org? If so, it is expected the ZIM might be incomplete, there is a 2h and 4GB limit on this free service to ensure fair use and access to everyone.

**Comment by vitaly-zdanevich** [comment]
> Did you created this ZIM through zimit.kiwix.org?

Yes, can I create it locally?

**Comment by kelson42** [comment]
Yes, this is FOSS
