### ISSUE TITLE
Site issue: https://africanstorybook.org/

### ISSUE THREAD

**Issue by ikreymer** [openzim/zimit#34]
The site is a SPA, with no unique URLs for the storybooks, making it difficult to capture.
However, the site does have downloadble pdfs/epubs.

**Comment by kelson42** [comment]
@ikreymer I believe here what we need now is a detailed explanation why it fails to render properly, so we could have a look to the problem at some point in the future.

**Comment by ikreymer** [comment]
The site, perhaps intentionally, does not provide unique links to each of the storybooks, instead they are loaded in a single-page app and the link is always `#`. While a custom behavior could be made that can capture them by clicking on the links, there would not be a way to link to each one, as the links would always go to the home page. The builtin search would of course not work, and neither would the ZIM search.

**Comment by kelson42** [comment]
Do I’m right to think this is a hopeless case?

**Comment by ikreymer** [comment]
I was about to say 'yes', but then I checked for a sitemap, and, good news, there is: https://www.africanstorybook.org/sitemap.xml

So, can add a `--useSitemap https://www.africanstorybook.org/sitemap.xml` flag that can parse it and just queue up the URLs listed there!

**Comment by ikreymer** [comment]
This looks very promising! Initial results seems to work, will need to add a `--useSitemap` flag to zimfarm @rgaudin

**Comment by rgaudin** [comment]
Did it.

**Comment by kelson42** [comment]
We should run on zimfarm and test, before closing.

**Comment by ikreymer** [comment]
Started a crawl on zimfarm now.
Also looked at various options for making links from home page linkable. Unfortunately, that won't work as they're loading partial HTML snippets, and not a full pages that are being crawled via the sitemap.

**Comment by rgaudin** [comment]
@ikreymer following-up on slack discussion ;

Regarding the query string options order ; that seem like a pretty common use case as those are by definition name-based and thus unordered. So we'd expect a lot of website to have discrepancies between links and fetched resources.
How does that work/not work with the current solution. How is that specific to AfricaStryBooks?

Could you elaborate on your last comment regarding those snippets? You mean in the homepage? Where are the snippets coming from?

**Comment by ikreymer** [comment]
The zimfarm crawl succeeded with a 52GB ZIM file, as expected.

Re: query argument sorting could be added as an extra canonicalization step in warc2zim.

However, it will not help with being able to browse titles from home page, as there is actually more than just query arg difference. The home page loads partial HTML snippet, while the sitemap includes links to full pages, so they are not the same.
Ex:
`https://africanstorybook.org/read/readbook.php?id=35703&d=0&a=1` -- HTML snippet loaded from home page, is not a full page.

`http://www.africanstorybook.org/reader.php?id=35703&a=1&d=0`  -- full URL from sitemap, but not linked to on the home page

**Comment by rgaudin** [comment]
Closing then ; right?
