### ISSUE TITLE
zimit.kiwix.org: https://plato.stanford.edu/ issues with linking back to remote version

### ISSUE THREAD

**Issue by TheWanderer1983** [openzim/zimit#361]
Hello,

When browsing my local kiwix version of plato.standford.edu all href links  display to the local instance correctly, but when I click them the page loads for a brief moment but then reloads the remote version of the page (plato.standford.edu). In firefox, if i open the links as a new tab it will correctly load and stay on the local kiwix version.

**Update**
I've now tried it with a standard ZIM the "Internet Encyclopedia of Philosophy" and it's doing the exact same thing. 
Regards
Dylan

**Comment by benoit74** [comment]
Which reader are you using? I strongly uspect you are using an "old" version of kiwix-serve (probably on a hotspot), only 13.1.0 version of kiwix-serve is operating properly with Zimit 2 ZIMs. Updating kiwix-serve or using another reader is the only solution.
