### ISSUE TITLE
Issue with html-load.com

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#377]
Looking at https://dev.library.kiwix.org/viewer#ancient.eu_en_all_2024-08 the zim looks ok at first but when we click on any link besides the cookie banner we get the following warning:
`Failed to load website properly since html-load.com is blocked. Please allow html-load.com`
![Screenshot 2024-08-30 at 15 15 57](https://github.com/user-attachments/assets/748a2fa6-cbfa-4a42-94f2-76812ef9863b)
And then after clicking ok the layout of that very same page appears all broken:
![Screenshot 2024-08-30 at 15 18 26](https://github.com/user-attachments/assets/41d9d609-e86c-4b55-a44e-c393665dd797)

**Comment by benoit74** [comment]
Please post such issues in original zim-request, content team should not open tickets in scrapers repo directly, I have to do a first analysis to confirm if it is a configuration issue or a scraper issue.

I'll close this for now as not planned until my analysis is done.
