### ISSUE TITLE
503 Service Temporarily Unavailable - zimit.kiwix.org

### ISSUE THREAD

**Issue by hamoudak** [openzim/zimit#378]
I had this message today when trying to open the website: 
503 Service Temporarily Unavailable
nginx

**Comment by kelson42** [comment]
@hamoudak Service is back

**Comment by hamoudak** [comment]
yes. I checked the website more than once. . thank you.

**Comment by benoit74** [comment]
It is important to note that we have very limited SLA on this free service, downtimes of few hours have to be expected from time to time.

**Comment by hamoudak** [comment]
I appreciate your explanation.
