### ISSUE TITLE
Custom Web user-agent

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#38]
We need to setup a custom browser agent and share the following info:
* ZIMIT scraper name
* email to contact

This could be added the the Standard Chrome User-Agent

**Comment by ikreymer** [comment]
Sure, that's easy to add as an option.

What do you have in mind, something like this?

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 +Zimit info@kiwix.org
```
Do you want to specify the whole user agent, or just the part to be added (in case the browser changes and then it can be updated separately)?

**Comment by kelson42** [comment]
@ikreymer Good to me. Just appending at the end. Should be a specific option of the scraper. On MWoffliner, this is mandatory and call —adminEmail.
