### ISSUE TITLE
ZIM files created with Zimit and displayed via kiwix-serve always have a white padding below the topbar

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#41]
A white padding of a few pixels height, quite visible. Tested with Firefox.

See here:
![image](https://user-images.githubusercontent.com/1029718/97270436-71ff0500-182f-11eb-85ab-b266d9726065.png)

This is ugly, unecessary and does not appear with other ZIM files. It should be removed.

**Comment by ikreymer** [comment]
This is coming from the padding-top `skin.css` in kiwix-serve. I guess it could be overriden, but assume it was set from some other calculation there?

```
body {
    padding-top: 3em !important;
}
```

**Comment by kelson42** [comment]
Then why it seems to be visible only in case of zimit zim?

**Comment by ikreymer** [comment]
I think it happens with other ZIMs too, ex:

<img width="1427" alt="Screen Shot 2020-10-27 at 2 49 57 PM" src="https://user-images.githubusercontent.com/1015759/97365953-bdcba180-1863-11eb-9990-b7ffcf51e646.png">

**Comment by kelson42** [comment]
Ok I will investigate why it fails as well on this youtbe based ZIM.

**Comment by kelson42** [comment]
@ikreymer I have tested and this is not the samee stuff: ubongo slides nicely (without white band) behind the taskbar if you scroll. Zimit don’t.

**Comment by ikreymer** [comment]
Yes, the scrolling happens in an iframe, which is fixed, so that's why it won't move, but it is there whenever you use kiwix-serve. To fix it, I think you just need to adjust the padding in kiwix-serve ui to be slightly smaller:

```
body {
    padding-top: 3em !important;
}
```
It wouldn't make sense to add a kiwix-serve specific override to the zims, since it would then be incorrect if the size of kiwix-serve bar later changes.

**Comment by ikreymer** [comment]
You could do something like `padding-top: calc(3em - 8px) !important`

**Comment by rgaudin** [comment]
This is upstream. Easily verifiable by adding `body { background-color: red; }` on any ZIM
See this fix: https://github.com/kiwix/kiwix-lib/pull/422
