### ISSUE TITLE
Favicon seems not always scraped properly

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#42]
My understanding was that if no custom favicon is given, the web site favicon will be taken and put to the ZIM favicon. This seems to be the right behaviour and this is what was happening with lesfondamentaux with previous scrape.

I have made a new scrape of lesfondamentaux (after having set custom title/description and change the default URL to `https://lesfondamentaux.reseau-canope.fr/` in place of `https://lesfondamentaux.reseau-canope.fr/accueil.html`) this morning and there is no ZIM favicon anymore:
![image](https://user-images.githubusercontent.com/1029718/97288612-5f43fa80-1846-11eb-8e3e-714605470777.png)

I don't know if there is a sporadic problem, a regression, a bug or a misunderstanding of me.

**Comment by rgaudin** [comment]
There are two problems I see:

* https://github.com/openzim/warc2zim/issues/67 this the `/` url being a redirect and thus warc2zim doesn't look for its favicon. That's why the ZIM has no favicon and that will get fixed there.
* `https://lesfondamentaux.reseau-canope.fr/fileadmin/template/img/favicon.ico` is missing from the ZIM. We've tested that on two different runs. Always 404. Don't have the WARC at hand to check the underlying cause but this is definitely a problem as this is a clear resource of the accueil page.

**Comment by ikreymer** [comment]
I've started a crawl with the starting page of `https://lesfondamentaux.reseau-canope.fr/accueil.html` instead of `https://lesfondamentaux.reseau-canope.fr/` to see if that also fixes the second issue somehow, just to test.

**Comment by ikreymer** [comment]
Can confirm that the icon is fine after changing the main page url to `https://lesfondamentaux.reseau-canope.fr/accueil.html`.
I think best solution is to disallow specifying a URL that is a redirect as the main URL (which should be rare?)

**Comment by kelson42** [comment]
Homepage redirects are not rare. Redirections should be handled properly IMO.

**Comment by rgaudin** [comment]
Agree with @kelson42 that homepage redirect are to be expected. I suggest we handle them in zimit with an addition preparation step:

``` py
actual_url = requests.head(url, follow_redirects=True, timeout=3)
if actual_url != url:
  if url.netloc != actual_url.netloc:
     raise ValueError("Out of scope main page target")
  else:
    url = actual_url
```

With this, we can expect warc2zim to fail on non-html homepage.

**Comment by rgaudin** [comment]
> Can confirm that the icon is fine after changing the main page url to `https://lesfondamentaux.reseau-canope.fr/accueil.html`.

Please provide an explanation for the favicon being 404 on the other scenario.
