### ISSUE TITLE
zimit fails to archive site

### ISSUE THREAD

**Issue by Aetohatir** [openzim/zimit#431]
I wanted to archive https://openwetware.org/wiki/Main_Page, however both the Docker image and the site version (zimit.kiwix.org) fail.
This was the request: https://zimit.kiwix.org/#/request/0c86a24a-9498-4c31-94ac-b50f4c943d4f

Any suggestion why?
Thank you.

**Comment by benoit74** [comment]
Website is protected by what looks like a very aggressive web application firewall. Requests from scraper are directly blocked. Not much we can do. Unless you can contact website owner to whitelist scraper IP, but this might not even be sufficient.
