### ISSUE TITLE
Zimming Debian failed

### ISSUE THREAD

**Issue by SZCZURek312** [openzim/zimit#443]
Tried to Zim wiki.debian.org from kiwix site but it failed. 
c76b1 https://zimit.kiwix.org/#/request/c76b159d-aab3-4bba-a6b0-2d1a459204a8

**Comment by benoit74** [comment]
wiki.debian.org is returning a 403 when crawling the home page from our zimit.kiwix.org worker. It works well from my dev machine, so not a software issue, and probably just so ban rules of wiki.debian.org on the IPs of our datacenter. Not something we can actively fix, at least not without someone donating another worker machine in another datacenter where wiki.debian.org would not block us.
