### ISSUE TITLE
No Zim created after exiting process?

### ISSUE THREAD

**Issue by pbz134** [openzim/zimit#448]
Hello,

I used zimit on https://en.touhouwiki.net (with --keep enabled) and it ran for 3 days, then I cancelled it.
However, I didn't get any Zim file after cancelling. Do I have to do anything specific to retrieve the zim file, or does the download need to finish before I can get the file?

**Comment by hamoudak** [comment]
don't use ctrl-c in the terminal; you won't find the crawl folder or any zim file  except "fails" folder . if you want to cancel, just close the window and zimit will end the crawl by it's own, then you'll find your crawl folder there not the zim file. another way is diconnecting your connection but I recommend to you the first method. and you need to let it finish to get the zim file.

**Comment by pbz134** [comment]
Got it, thanks for the reply!
