### ISSUE TITLE
Der Postillon not able to look at older posts

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#48]
Seen on https://tukasu.ml/der-postillon.com_fr_all_2020-10

At the bottom of the page there is a link to older posts (Ältere Posts) from the landing page which returns an error when clicked on:  `Sorry, the url https://www.der-postillon.com/search?updated-max=2020-10-27T17:15:00%2B01:00&max-results=12 is not found on this server`

![Capture d’écran 2020-11-04 à 17 30 04](https://user-images.githubusercontent.com/21675885/98138488-72e50600-1ec3-11eb-83d7-e38e92342a7c.png)

**Comment by ikreymer** [comment]
Looks like anything with `search?` in the URL was excluded from the crawl.. Hm, can try with it included, will lead to larger ZIM but probably needed if want the navigation to work.
The posts are still accessible via ZIM search likely.

**Comment by kelson42** [comment]
@ikreymer With the latest ZIM it seems to me that we have access to the older posts, but now I see endless requests to kiwix-serve:
![image](https://user-images.githubusercontent.com/1029718/98924391-0d9da000-24d5-11eb-9bf1-1bcb117cbbbe.png)

**Comment by ikreymer** [comment]
Hm, I can repro it, only in Firefox, probably from some ad.. Will see if there's anything that can be done...

**Comment by ikreymer** [comment]
Think I fixed the issue, involved a patch in the rewriting system, so will also need a patch to warc2zim.
Started a new crawl to test.

**Comment by kelson42** [comment]
@ikreymer Seems to work fine in the latest scrape indeed. Thank you! https://tukasu.ml/der-postillon.com_fr_all_2020-11
