### ISSUE TITLE
Does a zim file really leave tracking cookies?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#49]
Seen on devdocs.io, a floating window warning the user that tracking cookies are being used. 
![Capture d’écran 2020-11-04 à 17 33 08](https://user-images.githubusercontent.com/21675885/98138953-ed158a80-1ec3-11eb-95c9-39d924fa45fe.png)

- Are cookies really created?
- If not, then the floating warning window should probably be disabled.

**Comment by Popolechien** [comment]
There is a similar floating window on developer.mozilla.org
Maybe the whole thing is already addressed in warc2zim's [#61](../../warc2zim/issues/61)?

**Comment by rgaudin** [comment]
FYI, cookies are sent on the browser so a ZIM could of course place cookies. Not saying those are set here.

**Comment by ikreymer** [comment]
Yes, in this case, the cookie is set and accessed via javascript `document.cookie`.

Not sure of a way around this, other than presetting the cookie in a custom way for the page.
In this case, it the `analyticsConsent` cookie is set,
```
document.cookie
"analyticsConsentAsked=1; news=1578873600000; version=1603459474; analyticsConsent=1; count=2"
```
Of course, the cookie is only part of that path for the ZIM and nothing is sent anywhere

**Comment by kelson42** [comment]
Cookies are set and this is legitimate. Visial warning is almost non-sense to me in offline context. If confirmed, OK to consider as https://github.com/openzim/warc2zim/issues/61 dupkicate and close.
