### ISSUE TITLE
Disabled Devdocs pages fail to load

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#50]
All of them return the following error: 
![Capture d’écran 2020-11-04 à 17 35 52](https://user-images.githubusercontent.com/21675885/98139237-3e257e80-1ec4-11eb-9c78-14c07d46fe4b.png)

(to be clear on the source website they are fully available)

**Comment by rgaudin** [comment]
We could support those with a much larger ZIM ; or we could hide those using a custom CSS.

@kelson42 what do you suggest?

**Comment by ikreymer** [comment]
Yes, they were intentionally excluded from the crawl. Including them would result in significantly larger ZIM.

**Comment by kelson42** [comment]
What are these pages? Sounds weird to blacklist then for technical reasons id the have interesting content.

**Comment by Popolechien** [comment]
@kelson On the landing page that'd be every single one under the Disabled header
![Capture d’écran 2020-11-05 à 09 22 40](https://user-images.githubusercontent.com/21675885/98215877-9e5e0400-1f48-11eb-9327-8c0d1f2a4644.png)

**Comment by rgaudin** [comment]
@kelson42 can you answer so it's actionnable?

**Comment by kelson42** [comment]
We want everything.

**Comment by ikreymer** [comment]
Latest crawl should have all of them.. Note that some are not actually available until enabled through the UI.

**Comment by kelson42** [comment]
I believe this to work now at https://tukasu.ml/devdocs.io_en_all_2020-11/

**Comment by dan83g** [comment]
> I believe this to work now at https://tukasu.ml/devdocs.io_en_all_2020-11/

Try adding two docs to the main set and you will see that it doesn't work as it should.

**Comment by dan83g** [comment]
Try adding two extra items to the main set and you will see that it doesn't work as it should. Requests start linking to https://devdocs.io, which gives a 404 error.
