### ISSUE TITLE
Problem with ads

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#51]
See for instance https://tukasu.ml/courses.lumenlearning.com_en_all_2020-10/A/courses.lumenlearning.com/boundless-writing/chapter/word-choice/
![Capture d’écran 2020-11-04 à 17 52 43](https://user-images.githubusercontent.com/21675885/98141123-8e9ddb80-1ec6-11eb-85d9-f612ee6a51e4.png)

**Comment by ikreymer** [comment]
Yes, the add is likely going to be some dynamic URL. Maybe the best option is to disable a blank page with no message?
But, how to determine if its an add? Probably need a list of ad URLs, perhaps special handling, related to openzim/warc2zim#63

**Comment by kelson42** [comment]
I we agree that  openzim/warc2zim#63 is an acceptable approach and would fix this issue. OK to close this one as duplicate.
