### ISSUE TITLE
Find a domain name to host the public visible web site

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#55]

**Comment by Popolechien** [comment]
Ok quick search on godaddy:
zimit.io **X**
offline.io **X**

offline.it **X**
zim.it **X**
youzim.it **✓** (CHF 12.76; then 14.72/year)

zimit.kiwix.org **✓**

zimit.online **✓** (CHF 1.16; then 49.33/year)
zimitup.online **✓** (CHF 1.16; then 49.33/year)

zimit.site **✓** (CHF 1.16; then 39.50/year)
zimit.xyz **✓** (CHF 1.16; then 14.33/year)
zimit.shop **✓** (CHF 3.13; then 44.43/year)
zimit.live **✓** (CHF 2.15; then 31.64/year)
zimit.tech **✓** (CHF 10.02; then 69.-/year)
zimit.today **✓** (CHF 2.15; then 27.71/year)
zimitup.com **✓** (CHF 0.99; then CHF 19.57/year)

offline.services **X**
zim.services **✓** (CHF 11.98; then 41.46/year)
zimit.services **✓** (CHF 11.98; then CHF 41.48/year)

Ultimately we'll need to decide what the use case/business model for it is.

**Comment by kelson42** [comment]
@rgaudin, both Stéphane and me are in favour of `youzim.it`. OK for you?

**Comment by rgaudin** [comment]
Sure!
