### ISSUE TITLE
problem deploying edu.gcfglobal.org_en_all_2020-12

### ISSUE THREAD

**Issue by tim-moody** [openzim/zimit#57]
I built edu.gcfglobal.org_en_all_2020-12 using the command from https://farm.openzim.org/recipes/edu.gcfglobal.org_en, namely

`docker run -v /my-path:/output:rw --name zimit_edu.gcfglobal.org_en --detach --cpu-shares 3072 --memory-swappiness 0 --memory 4294967296 --shm-size 4294967296 --cap-add SYS_ADMIN --cap-add NET_ADMIN openzim/zimit:dev zimit --exclude="(\?q=|/signin)" --lang="eng" --name="edu.gcfglobal.org_en_all" --output="/output" --scope="https://edu.gcfglobal.org/en/" --url="https://edu.gcfglobal.org/en/topics/" --verbose --workers="6" --title="200+ Free Tutorials" --description="Tutorials in technology, reading, math, career & more" --favicon="https://sites.google.com/site/tricountyassistivetechnology/life-skills/gcflearnfree.jpg" --adminEmail="contact+zimfarm@kiwix.org"`

The zim built with no complaints

I deployed it at http://iiab.me/kiwix/edu.gcfglobal.org_en_all_2020-12/A/index.html on kiwix-serve version 3.1.2 x86. Search returns results, but access to a page yields

This page must be loaded via an HTTPS URL to support service workers.

We don't really want https for offline servers as self signed certs give scary messages to users. Is this a requirement?

**Comment by holta** [comment]
A Big Thank You to @tim-moody and @kelson42 and @shanti-bhardwa and @ericnitschke and everyone working on this!

Related: https://github.com/openzim/zim-requests/issues/225

**Comment by tim-moody** [comment]
To quote from https://developers.google.com/web/fundamentals/primers/service-workers:

You need HTTPS
During development you'll be able to use service worker through localhost, but to deploy it on a site you'll need to have HTTPS setup on your server.

Using service worker you can hijack connections, fabricate, and filter responses. Powerful stuff. While you would use these powers for good, a man-in-the-middle might not. To avoid this, you can only register service workers on pages served over HTTPS, so we know the service worker the browser receives hasn't been tampered with during its journey through the network.

**Comment by kelson42** [comment]
@tim-moody This has to run in HTTPS. This kind of ZIM file uses service workers. Browser implementation of service workers requires HTTPS on remote hosts. There is nothing we can do about that. Works as designed.

**Comment by tim-moody** [comment]
@kelson42 can we assume then that it was not designed for offline use?

**Comment by kelson42** [comment]
@tim-moody You can assume it, we don't.
