### ISSUE TITLE
Feature Request: https required flag

### ISSUE THREAD

**Issue by tim-moody** [openzim/zimit#58]
Please add a tag or field to the zim catalog which indicates whether https is required for the zim to work.

**Comment by kelson42** [comment]
@tim-moody I think wehave a tag _sw?!

**Comment by kelson42** [comment]
We should as well maybe update the Readme here as this restriction is not obvious.

**Comment by tim-moody** [comment]
"edu.gcfglobal.org_en_all": {
    "file_name": "edu.gcfglobal.org_en_all_2020-12",
    "menu_item": null,
    "article_count": "3",
    "media_count": "26844",
    "size": "969M",
    "tags": "_ftindex:yes;_category:other;_sw:yes;_pictures:yes;_videos:yes;_details:yes",
    "language": "en",
    "zim_date": "2020-12-01"

**Comment by kelson42** [comment]
Good, then I will update the doc and close the ticket.
