### ISSUE TITLE
Feature Request: expose development mode for warc based zims

### ISSUE THREAD

**Issue by tim-moody** [openzim/zimit#59]
https://developers.google.com/web/fundamentals/primers/service-workers mentions the need for https during deployment, but states:

_During development you'll be able to use service worker through localhost,_ 

Can we have such a development mode for use on a private lan?

**Comment by kelson42** [comment]
@tim-moody This already works without HTTPS on http://localhost. Give it a try with kiwix-serve. All of this is anyway handled in the browser, we have no control on it.
