### ISSUE TITLE
Scrape as a mobile device

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#6]
If the ZIM we made so far with warc2zim work on Android with Kiwix, the layout is not adatped. We should probably have an option to specify which kind of display resolution browsertrix should use. Per default we probably should have a mobile (which one exactly?) screen resolution.

**Comment by ikreymer** [comment]
Sure, this can be added as an option

**Comment by ikreymer** [comment]
There's a lot of options for this, not sure which one you want as default =)

Can specify a device by name from this list:
https://github.com/puppeteer/puppeteer/blob/main/src/common/DeviceDescriptors.ts

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteerdevices

**Comment by kelson42** [comment]
@ikreymer The offline scrape should offer the best UX for most users. I believe the best path to that is to do a mobile scraping. This should be the default behaviour. I let you decide about the best ua/resolution (which seems to me the key values).

**Comment by rgaudin** [comment]
I think it'd be wiser to have a single option `--as-device` with a default value that @ikreymer will choose (something mobile).
That seems more than enough for now and would be clear to all.
