### ISSUE TITLE
--adminEmail is not a supported argument

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#61]
But this is part of the Zimfarm UI options. See https://farm.openzim.org/pipeline/15502f736370cfd45e0e0df5/debug

**Comment by kelson42** [comment]
@rgaudin Not sure if this is a bug for zimfarm or zimit.

**Comment by rgaudin** [comment]
You created a recipe using the `:latest` docker image. As explained during last meeting, all work happened on `:dev` and we are about to release first version (`:1.0` and `:latest`) very soon (tomorrow).

**Comment by Popolechien** [comment]
@rgaudin 
> You created a recipe using the `:latest`

I actually did. As long as we don't have a clear user manual I'm bound to hack around without knowing much what I'm doing (at least not as long as I only create recipes once a month) :-)
