### ISSUE TITLE
"Serviceworkers not accepted" error message

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#64]
Trying zimit on https://mesquartierschinois.wordpress.com returns a 16Mb file with the icon but that cannot be opened
![image](https://user-images.githubusercontent.com/21675885/101905438-c11eb080-3bb7-11eb-8079-add0a95f7b4d.png)

**Comment by rgaudin** [comment]
Unless you can reproduce this on kiwix-server, that should probably be moved to kiwix-desktop.

**Comment by Popolechien** [comment]
Good point: I have the same issue on Kiwix-JS, macOS, but it worked on Android.
