### ISSUE TITLE
Add limit-hit information to progress

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#65]
We shall be able to know whether the `--limit` information (that is passed to the crawler) has been hit or not.

**Comment by kelson42** [comment]
@Popolechien Can you please tell us:
* what should be written in the email
* What should be displayes on the screen

... if the quota is reached.

**Comment by Popolechien** [comment]
Information could be along the lines of
"You have reached the maximum number of pages (1,000) allowed for free crawling. [Contact us](https://www.kiwix.org/en/contact/) to help us purchase additional server space for you".

Should work for both email and web.

**Comment by kelson42** [comment]
@rgaudin Inguess we can close that one because of #85?

**Comment by rgaudin** [comment]
That's right.
