### ISSUE TITLE
Where are the Kiwix-Desktop settings?

### ISSUE THREAD

**Issue by srousset** [openzim/zimit#67]
Hi Kiwix team, here's Dumbo with a trivial question.

I've just discovered [the Zimit website](https://youzim.it), and it tells me that "If using Kiwix-Desktop, then you will need to configure it as a Kiwix-serve instance in the settings." So, my dumb question is: where are those settings? I have Kiwix-Desktop version 2.1.2 (2.1.6) for macOS, and I see no _Settings_ or _Preferences_ option in any menu.

Best regards, Stéphane

**Comment by kelson42** [comment]
@srousset Thank you for your question. The FAQ means Kiwix Desktop for Windows and GNU/Linux. Kiwix Desktop for macOS is a totally different code base, a ticket is open there to add support of service worker based ZIM files https://github.com/kiwix/apple/issues/342. Will move this ticket to openzim/zimit-frontend to fix the FAQ wording.
