### ISSUE TITLE
Create and tests ZIM files

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#7]
Bellow is the list of root URLs to create and test ZIM files off, using zimit's core docker image.
Zimfarm recipes (with appropriate metadata) will be created for each. Original list is on [zim-requests](https://github.com/openzim/zim-requests/issues?q=is%3Aopen+is%3Aissue+label%3Azimit)

```
http://bouquineux.com/
https://lesfondamentaux.reseau-canope.fr/accueil.html
http://www.manioc.org/
https://www.der-postillon.com/
https://edu.gcfglobal.org/en/topics/
https://cheatography.com/
https://stacks.math.columbia.edu/
https://africanstorybook.org/
https://devdocs.io/
https://developer.mozilla.org/en-US/
https://journals.openedition.org/bibnum/
https://www.lowtechmagazine.com/
https://www.musictheory.net/lessons
https://courses.lumenlearning.com/catalog/boundlesscourses
```

**Comment by ikreymer** [comment]
Status (checked if successfully crawled so far):
Issues for other will be noted:

- [x] - http://bouquineux.com/
- [x] - https://lesfondamentaux.reseau-canope.fr/accueil.html
- [ ] - http://www.manioc.org/
- [ ] - https://www.der-postillon.com/
- [ ] - https://edu.gcfglobal.org/en/topics/
- [ ] - https://cheatography.com/
- [x] - https://stacks.math.columbia.edu/
- [ ] - https://africanstorybook.org/
- [ ] - https://devdocs.io/
- [x] - https://developer.mozilla.org/en-US/
- [x] - https://journals.openedition.org/bibnum/
- [ ] - https://www.lowtechmagazine.com/
- [x] - https://www.musictheory.net/lessons
- [x] - https://courses.lumenlearning.com/catalog/boundlesscourses

**Comment by rgaudin** [comment]
Recipes created in zimfarm for all of those. Filter using the `zimit` tag in https://farm.openzim.org/recipes

**Comment by ikreymer** [comment]
Created separate issues for sites that don't work:
#33 - manioc.org
#34 - africastorybook.org
#35 - devdocs.io

**Comment by rgaudin** [comment]
Thanks ; opened #32 as well and created https://github.com/openzim/zimit/wiki/Matrix
I will add a kiwix-serve to serve those and @Popolechien will look at all of them from a user's perspective.

**Comment by Popolechien** [comment]
Well here's what I get so far for all of them:
![Capture d’écran 2020-10-21 à 16 58 23](https://user-images.githubusercontent.com/21675885/96738187-c2eda400-13be-11eb-8d85-8d733ef9b3cb.png)
(Loading https leads to `ERR_CONNECTION_CLOSED`)

**Comment by rgaudin** [comment]
My bad, it's now fixed
