### ISSUE TITLE
Failure to zim lutzmoeller.net

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#73]
See https://farm.youzim.it/pipeline/5fc6e08cb20014d7bd6faef5/debug

Fails to even start. I see the zim title has a special character (ö) in it: could it be a reason?

**Comment by rgaudin** [comment]
No it's not the reason. As you can see, the person set a custom `mobileDevice` of `android` which is not supported.

```
Unknown device: android
```

The list of valid values for this is [available here](https://github.com/puppeteer/puppeteer/blob/main/src/common/DeviceDescriptors.ts)

Closing as it's an incorrect use of an advanced option.

**Comment by Popolechien** [comment]
Well https://farm.youzim.it/pipeline/f4d6e08cb20014d7a69faef5/debug failed all the same but this time because of an SSL error.
Anything we can do or it's out of our hands?

**Comment by rgaudin** [comment]
https://lutzmoeller.net has an expired SSL certificate… This website is available on plain HTTP as well, you should use that URL
