### ISSUE TITLE
Menu items auto-close and can't be used

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#74]
Made a zim out of http://lutzmoeller.net and got https://farm.youzim.it/pipeline/9f30e0a7cf65533f2590bef5

The zim is fine, except that (at least on android) the menu items, when tapped, open for about a second and then close immediately, making it nigh impossible to reach the submenu items shown below. There something somewhat similar on mobile (online) view, but not as bad.

![image](https://user-images.githubusercontent.com/21675885/103364460-28949580-4abe-11eb-881c-5e9c8a30f6f5.png)

**Comment by rgaudin** [comment]
I can reproduce it with the online version and Chrome using responsive mode *Pixel2* (don't have an android at hand).

This is a website bug, not a zimit one. You can try to generate other versions of the ZIM playing with the *As device* option and see if there's any improvement.
