### ISSUE TITLE
zimit refuses to pull pdf files stored on wordpress site

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#81]
Ran a zimit session of https://educate.gov.jm/index.php/resources/
The page is pretty straitghtforward inasmuch as it is a wordpress site with a list of links. Each link is to a pdf file.

Zimit copied the landing page ([here is the recipe](https://farm.youzim.it/pipeline/f95550a4ef42d7d04efca006)) but failed to collect the PDF files behing the links (only returned `net::ERR_FAILED`)

**Comment by kelson42** [comment]
@ikreymer Sounds like a problem with the spider. Would you be able to confirm?

**Comment by kelson42** [comment]
@rgaudin Can we link this please with an upstream ticket?

**Comment by rgaudin** [comment]
This is eventually a recipe mistake as the PDF files, while on the same domain name, are *below* the home page and thus the default scope:

* https://educate.gov.jm/index.php/resources/ is the home and scope
* https://educate.gov.jm/wp-content/uploads/2021/01/eHome-School-Network-Broadcast-Schedule-Week-2-January-11-15-2021-FINAL.pdf is where content is

You can fix the recipe by setting the `--scope` param to `https://educate.gov.jm/`
