### ISSUE TITLE
is --exclude not yet implemented?

### ISSUE THREAD

**Issue by myt00seven** [openzim/zimit#82]
Hello I'm a user of the zimit tool and I love it. The readme indicates that the '--exclude' feature is there but I couldn't get it working after trying all possible variants of my regex expression. I then look into the code base and found that this feature doesn't seem to be implemented yet. 

For example, the source code to the current zimit.py shows there is a 'scope' argument that is being used to [check if the URL is within the same scope](https://github.com/openzim/zimit/blob/c3a7a021214ac4983e5f02c649390c9aa4ea94a6/zimit.py#L188) as regex filter. However, I didn't see any lines that are actually using the 'exclude' feature to apply the regex filter to the current URLs. 

Could someone confirm that it is not yet implemented or it is just because I'm looking at the wrong place. I would like to contribute to the project if it is the first case. 

Thanks!

**Comment by rgaudin** [comment]
It is implemented and in use. 
Please look at [this recipe](https://farm.openzim.org/recipes/lowtechmagazine.com/config) for an example usage.

**Comment by rgaudin** [comment]
So in this example, the string passed to zimit is `(\?q=|signup-landing\?|\?cid=)` which matches three different url parts:

- `?q=`
- `signup-landing?`
- `?cid=`

That should give you enough information on the expected format for the regexp. Those are 3 different excludes (not an intersection). We should probably improve the help description with an example.
