### ISSUE TITLE
Kiwix website incorrectly listed as Redirecting...

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#86]
Ran zimit on www.kiwix.org and got this:
![screen kiwix](https://user-images.githubusercontent.com/21675885/109162352-650c0700-7778-11eb-9ab7-96297949f162.jpg)

**Comment by rgaudin** [comment]
Well, that's what the Kiwix homepage is about…

```html
curl -v https://www.kiwix.org

< HTTP/2 200
<
<!DOCTYPE html>
<html>
	<head>
		<title>Redirecting...</title>
		<meta http-equiv="refresh" content="0;url=https://www.kiwix.org/en/">
	</head>
	<body>
		<script type="text/javascript">
			window.location = "https://www.kiwix.org/en/";
		</script>

		<p>You are being redirected to <a href="https://www.kiwix.org/en/">https://www.kiwix.org/en/</a></p>
	</body>
</html>
```

Two distinct issues:

- HTML redirect is poor design for this use case. Kiwix website should probably use an HTTP redirect instead.
- Your recipe should use the redirected location. I think it's good practice to copy-paste from a working URL in your browser ; removes potential for typos.

We already handle HTTP redirect but we won't detect those are this is *content* http-wise.
