### ISSUE TITLE
produced zim files does not show up on kiwix-serve

### ISSUE THREAD

**Issue by yekanchi** [openzim/zimit#87]
it only works on kiwix-android while kiwix-serve does not show anything and prompt for https. mean while kiwix-sere does not support https. any work around to use it under kiwix-serve?

**Comment by rgaudin** [comment]
Can you give more details? There's no reason for it to not *show-up* in kiwix-serve. Screenshot maybe?

Can you try running Kiwix serve on your machine and accessing it via http://localhost:xxxx where xxxx is the port on which you started kiwix-serve?

There are some issues with reading those ZIMs (as indicated in the README) but it's not what you're describing.

**Comment by yekanchi** [comment]
the page shows this: 

the page must be loaded via an HTTPS URL to support service workers
try loading HTTP URL?

**Comment by rgaudin** [comment]
OK, you're not accessing it via `localhost`. Try accessing it from the same machine, using `localhost` as hostname. If you can't, then you have to proxy it behind an HTTPS web browser (https://caddyserver.com is convenient for this) because as you noted, kiwix-serve only works in HTTP for now (see https://github.com/kiwix/kiwix-tools/issues/416)

**Comment by yekanchi** [comment]
i am accessing it from localhost and it shows the message but something i found out right now is that if i use it on my internet machine in works fine but it does not work in offline machine.

**Comment by yekanchi** [comment]
> OK, you're not accessing it via `localhost`. Try accessing it from the same machine, using `localhost` as hostname. If you can't, then you have to proxy it behind an HTTPS web browser (https://caddyserver.com is convenient for this) because as you noted, kiwix-serve only works in HTTP for now (see [kiwix/kiwix-tools#416](https://github.com/kiwix/kiwix-tools/issues/416))

i will try this soluti

**Comment by yekanchi** [comment]
> OK, you're not accessing it via `localhost`. Try accessing it from the same machine, using `localhost` as hostname. If you can't, then you have to proxy it behind an HTTPS web browser (https://caddyserver.com is convenient for this) because as you noted, kiwix-serve only works in HTTP for now (see [kiwix/kiwix-tools#416](https://github.com/kiwix/kiwix-tools/issues/416))

using caddy reverse-proxy works fine in localhost but it does not work when someone connects from remote host

**Comment by dan83g** [comment]
it works fine with reverse-proxy

**Comment by kelson42** [comment]
I guess we can close this ticket now?

**Comment by yekanchi** [comment]
> it works fine with reverse-proxy (nginx)
> nginx.conf
> 
> ```
>     server {        
>         server_name 0.0.0.0;
>         
>         listen       443 ssl;        
> 
>         ssl on;
>         ssl_certificate     /ssl/site.crt;
>         ssl_certificate_key /ssl/site.key;                    
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;                
> 
>         location / {
>             proxy_pass http://kiwix;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-Real-Ip $remote_addr;            
>             proxy_set_header HOST $host;
>             proxy_set_header PORT $server_port;
>             proxy_redirect off;
>         }
>     }
> ```

thanks but actually i am using windows witch is not well with ngnix, as i said i tried caddy, and i alos now tried IIS reverse proxy but it does not work for remote case.
