### ISSUE TITLE
Video/Media Behaviors

### ISSUE THREAD

**Issue by ikreymer** [openzim/zimit#9]
Ensure embedded videos are capture (video tag, youtube) are captured if encountered on the page.

**Comment by kelson42** [comment]
@ikreymer What is the details nature of the problem we deal with here? I kind of assumed videos were working as this one of the first impressive things we had in the dev of `warc2zim`.

**Comment by rgaudin** [comment]
I couldn't capture lesfondamentaux with current zimit. It doesn't capture the video. Tried with [embed page](https://lesfondamentaux.reseau-canope.fr/embed/limparfait-un-temps-regulier.html) as well. It seems that the JS code create the `<video />` tag so maybe it's a `--waitUntil` issue? How did you create yours?

**Comment by ikreymer** [comment]
This is not yet fully finished, but should work on lesfondamentaux.

Try the latest version from this branch: https://github.com/openzim/zimit/tree/config-opts

The command line I used was:

```
docker run -d -v  ${PWD}/output:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb openzim/zimit --workers 6 --url  https://lesfondamentaux.reseau-canope.fr/accueil.html
```

You can add a `--limit 20` to just try a few pages.

**Comment by rgaudin** [comment]
OK, FYI, didn't work on the embed URL

```sh
docker build . -t zimit && \
    docker run -v $HOME/data/zimit/out:/output \
    --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --shm-size=1gb zimit \
    --workers 6 --limit 200 --url https://lesfondamentaux.reseau-canope.fr/embed/limparfait-un-temps-regulier.html
```

Maybe there's something different about the embed. I'll check again on next iteration.

**Comment by rgaudin** [comment]
FYI I launched it on whole fondamentaux with lastest code and it worked fine.

**Comment by ikreymer** [comment]
Autoplaying of youtube and regular videos (that don't preload) will likely be needed for at least the following sites:
- https://www.der-postillon.com/
- https://edu.gcfglobal.org/en/topics/
- https://manioc.org/

and possibly a few others that use video. The goal is to ensure youtube videos autoplay and other videos started manually as well.

**Comment by ikreymer** [comment]
> @ikreymer What is the details nature of the problem we deal with here? I kind of assumed videos were working as this one of the first impressive things we had in the dev of `warc2zim`.

Sorry, forgot to respond! The default behavior already captures videos that autoplay on their own with a `<video>` tag, such as fondamentaux.
This new work also captures videos that don't autoplay (by grabbing the URL directly) and also videos with custom embeds, like youtube.
