### ISSUE TITLE
fails to display embedded PDF files

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#90]
Tested on https://www.becepastquestions.com/
Looking at the maths section I see that the embedded PDF files (see e.g. https://www.becepastquestions.com/maths/bece-past-questions-answers-2014-maths/) are not displayed.

**Comment by rgaudin** [comment]
It's an iframe displaying a googledoc URL. I'm not sure if iframes are considered resources or pages. If the later, those would be excluded by the *scope* of the scrape.

```
//docs.google.com/viewer?url=http%3A%2F%2Fwww.becepastquestions.com%2Fwp-content%2Fuploads%2F2016%2F06%2FBece-Past-Questions-Answers-2014-Maths-Part1.docx&hl=en_US&embedded=true
```

**Comment by Popolechien** [comment]
I used youzim.it - would that scope be broader if I created the recipe directly in the zimfarm?

**Comment by rgaudin** [comment]
No, the scope is the URL domain unless you specify otherwise in the `--scope`. As I wrote earlier, I *don't know* if the scope is applied to iframe sources or not.

**Comment by kelson42** [comment]
> As I wrote earlier, I _don't know_ if the scope is applied to iframe sources or not.

@ikreymer Can you answer this question please?

**Comment by rgaudin** [comment]
Scope is applied to every request
