### ISSUE TITLE
Zimit not scraping cyrillic text

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#91]
Target website was https://sattvinfo.net/ - a russian website on Satellite TV apparently. The zimit job is [here](https://farm.youzim.it/pipeline/d1cf37b8e04fdbdaa8c8f406) and worked fine, except for the part where it did not pick up any of the cyrillic. Could it be they use non-standard font and zimit does not know how to fall back to default?

![Screenshot_20210325_102222_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/112450063-4471a580-8d54-11eb-8d59-71508c1b8ad5.jpg)

**Comment by rgaudin** [comment]
Thank you, I opened an upstream ticket https://github.com/webrecorder/browsertrix-crawler/issues/36

**Comment by ikreymer** [comment]
The fix is now part of wabac.js 2.6.8, updating to that version in warc2zim should fix the issue.

**Comment by kelson42** [comment]
@ikreymer great, thx!

**Comment by kelson42** [comment]
@rgaudin can we close this?

**Comment by rgaudin** [comment]
Fixed
