### ISSUE TITLE
Trying to navigate https://bse.belajar.kemdikbud.go.id/ returns session timeout

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#92]
The [website ](https://bse.belajar.kemdikbud.go.id/) is a glorified selection of PDF files, nothing fancy.
![Screenshot_20210415_205933_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/114923987-c0c84780-9e2d-11eb-9fd5-b7dfbf2bafc6.jpg)

**Comment by rgaudin** [comment]
mind sharing the zimfarm link?

**Comment by Popolechien** [comment]
Here we go: https://farm.youzim.it/pipeline/5a0882ffdb8124dbfdb88706

**Comment by rgaudin** [comment]
I'm getting Error Popups on the actual website as well, but I can access the content and read the PDF.

It seems that they are using a service worker themselves and that might be why it can't load properly:

```
Failed to load ‘http://localhost:9999/bse.belajar.kemdikbud.go.id_4859e671/A/mp_/https://bse.belajar.kemdikbud.go.id/lib/icheck/js/icheck.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘too much recursion’.
```

It also appears to be using web sockets, so definitely not *not fancy*

**Comment by Popolechien** [comment]
I take it you are on Kiwix-serve? I only tried on Android.

**Comment by rgaudin** [comment]
yes
