### ISSUE TITLE
Unable to copy yahoo answers

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#93]
Request [57378](https://farm.youzim.it/pipeline/573782bd9d41d392d6121806) for [Yahoo Answers](https://answers.yahoo.com/) yielded absolutely nothing - event the landing page cannot be loaded (on Android) with only the notification `net::ERR_FAILED`

The service will be discontinued May 5th, so mostly posting for reference.

**Comment by ikreymer** [comment]
Hm, we've tested Yahoo Answers with latest browsertrix crawler and it should generally work - scrolling through all answers is a bit tricky, but generally should be working. Perhaps there was a connection issue, or something was blocked?

**Comment by kelson42** [comment]
@Popolechien Can you make a new run please?
@ikreymer I see you made a new release 0.3.0... AFAIK we don't use it.
@rgaudin Should we maybe upgrade to 0.3.0 ?

**Comment by Popolechien** [comment]
@kelson42 Ran it again. [Similar result](https://s3.us-west-1.wasabisys.com/org-kiwix-zimit/other/answers.yahoo.com_cc59e671.zim) with a 350KB file (except this time no page opens whatsoever)
@ikreymer the log from the previous run is here: https://farm.youzim.it/pipeline/f3b6826328edd6487e04e706/debug

**Comment by Popolechien** [comment]
Service has been deprecated - issue is now moot.
